/**
 * OG görseli için gömülü font — T-028.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * NEDEN GÖMÜLÜ, NEDEN BU FONT
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * ÖLÇÜLDÜ: `@vercel/og`in birlikte geldiği varsayılan font
 * (`noto-sans-v27-latin-regular.ttf`) TÜRKÇE HARFLERİ İÇERMİYOR — İ (U+0130),
 * ğ (U+011F), Ğ, ş (U+015F), Ş eksik; yalnızca ı, ç, ö, ü var. Font
 * verilmezse `satori` eksik harfleri `fonts.googleapis.com`tan indirmeye
 * çalışır: üretimde AĞ BAĞIMLILIĞI, çevrimdışı ortamda ise boş kare.
 * "Yazılım Geliştirme" gibi bir başlık sessizce bozulurdu.
 *
 * Depodaki `src/app/fonts/space-grotesk.woff2` tam Türkçe kapsamına sahip ama
 * `satori` WOFF2 OKUMAZ — yalnızca TTF/OTF. Bu yüzden AYNI font TTF'e
 * çevrilip Latin-1 + Türkçe + tipografik noktalama ile alt kümelendi: 26 KB.
 * Yeni bir yazı tipi getirilmedi; lisans ve görünüm depodakiyle aynı.
 *
 * DOSYA OLARAK DEĞİL BASE64 OLARAK: `output: 'standalone'` derlemesi yalnızca
 * izlenen dosyaları kopyalar; `fs.readFileSync` ile okunan bir varlık
 * `outputFileTracingIncludes` ayarı gerektirirdi — o ise `next.config.ts`,
 * yani ORTAK DOSYA. Modül olarak gömmek bu bağımlılığı tamamen kaldırıyor.
 *
 * YENİDEN ÜRETMEK İÇİN (gizemli ikili dosya bırakmamak adına):
 *   fonttools ttLib.woff2 decompress src/app/fonts/space-grotesk.woff2
 *   pyftsubset src/app/fonts/space-grotesk.ttf \
 *     --unicodes="U+0020-007E,U+00A0-00FF,U+011E-011F,U+0130-0131,\
 *                 U+015E-015F,U+2013-2014,U+2018-201D,U+2026" \
 *     --drop-tables+=GSUB,GPOS --output-file=og-font.ttf
 */

const OG_FONT_BASE64 =
  'AAEAAAARAQAABAAQR0RFRgMXAxgAAD40AAAAXkhWQVIK1QRBAAA+lAAAATNPUy8yEenz8wAAO/QAAABgU1RBVHmTa0kAAD/IAAAA' +
  'KmF2YXIABQABAAA/9AAAABZjbWFwkZtt6wAAPFQAAAG4ZnZhcoKmaZIAAAMQAAAALGdhc3AAAAAQAAA+LAAAAAhnbHlmNIpBvAAA' +
  'AzwAADK8Z3ZhclTfarAAAEAMAAAmImhlYWQt3X3pAAA38AAAADZoaGVhCF0B+gAAO9AAAAAkaG10eMp0Kb8AADgoAAADqGxvY2E0' +
  'qCggAAA2GAAAAdZtYXhwAPsAwwAANfgAAAAgbmFtZS4SSHcAAAEcAAAB8nBvc3T/nwAyAAA+DAAAACAAAAAJAHIAAwABBAkAAADE' +
  'AAAAAwABBAkAAQAmAMQAAwABBAkAAgAOAOoAAwABBAkAAwA2APgAAwABBAkABAAmAMQAAwABBAkABQAaAS4AAwABBAkABgAkAUgA' +
  'AwABBAkBAAAMAWwAAwABBAkBBAAIAXgAQwBvAHAAeQByAGkAZwBoAHQAIAAyADAAMgAwACAAVABoAGUAIABTAHAAYQBjAGUAIABH' +
  'AHIAbwB0AGUAcwBrACAAUAByAG8AagBlAGMAdAAgAEEAdQB0AGgAbwByAHMAIAAoAGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUA' +
  'YgAuAGMAbwBtAC8AZgBsAG8AcgBpAGEAbgBrAGEAcgBzAHQAZQBuAC8AcwBwAGEAYwBlAC0AZwByAG8AdABlAHMAawApAFMAcABh' +
  'AGMAZQAgAEcAcgBvAHQAZQBzAGsAIABMAGkAZwBoAHQAUgBlAGcAdQBsAGEAcgAyAC4AMAAwADAAOwBGAEsAOwBTAHAAYQBjAGUA' +
  'RwByAG8AdABlAHMAawAtAEwAaQBnAGgAdABWAGUAcgBzAGkAbwBuACAAMgAuADAAMAAwAFMAcABhAGMAZQBHAHIAbwB0AGUAcwBr' +
  'AC0ATABpAGcAaAB0AFcAZQBpAGcAaAB0AEIAbwBsAGQAAAABAAAAEAACAAEAFAABAAh3Z2h0AlgAAAJYAAACvAAAAAABAAEEAAAC' +
  'vAAAAAIAFAAAAmUCvAAHAAsAADMTMxMjJyEHEzMDIxTA0cB8Kv77KkbNXhECvP1EoKABDgFjAAADAC4AAAJrArwAGQAjAC0AADM1' +
  'MxEjNSEyFhYVFRQGBgcVHgIVFRQGBiMnMzI2NTU0JiMjNTMyNjU1NCYjIy5eXgFmP181JDIXFzUlN18+k4UwOTgxhYQuOTkuhGoB' +
  '6GorTzcJMD4iBxEGIT8yCjlTLG0vKwkrL20uKQopLgABADT/8gJXAsoAHwAABSImNTU0NjMyFhUVIzU0JiMiBhUVFBYzMjY1NTMV' +
  'FAYBTICYmICAi3ZJTEpVVUpMSXaLDpGIpoiRjHoGCUJVW1CqT1xVQhEOeowAAgAuAAACawK8AA0AFwAAMzUzESM1ITIWFRUUBiMn' +
  'MzI2NTU0JiMjLl5eAR2MlJSMR0hVUlJVSGoB6GqOjoSOjm1YU4tVVwAAAQBFAAACCAK8AAsAADMRIRUhFSEVIRUhFUUBvv67ASn+' +
  '1wFKArxtuG29bQABAEUAAAH5ArwACQAAMxEhFSEVIRUhEUUBtP7FASL+3gK8bblu/tgAAQA0//ICVgLKACcAAAUiJiY1NTQ2MzIW' +
  'FRUjNTQmJiMiBhUVFBYzMjY1NSM1IREjNSMOAgE4SnVFmICAinYgQjJKVVVMTEaxASduEQgiPw5BfVumiJGJdAQIKEAlW1CqT15S' +
  'QAxm/qBFEicaAAABAEUAAAJLArwACwAAMxEzESERMxEjESERRXkBFHl5/uwCvP7aASb9RAEo/tgAAQBFAAAAvgK8AAMAADMRMxFF' +
  'eQK8/UQAAQAi//ICMwK8ABUAAAUiJjU1MxUUFjMyNjURIzUhFSMRFAYBCmt9eDg1MjN4AT9OdA51az8/NDw8NAF9bW3+g21zAAAB' +
  'AEUAAAJoArwADAAAMxEzETMTMwEBIwMjEUV5EfSb/s8BO5/6EQK8/uMBHf6n/p0BI/7dAAABAEUAAAIGArwABQAAMxEzESEVRXkB' +
  'SAK8/bFtAAABAEUAAAMoArwADwAAMxEzEzMTMxEjESMDIwMjEUXhiBGJ4HQRiMiIEQK8/ZUCa/1EAmX9mwJl/ZsAAQBFAAACVwK8' +
  'AAsAADMRMxMzETMRIwMjEUXmpRB35aURArz9lQJr/UQCa/2VAAIANP/yAm4CygANABsAAAUiJjU1NDYzMhYVFRQGJzI2NTU0JiMi' +
  'BhUVFBYBUYKbm4KDmpqDTldXTk1XVw6RiKaIkZGIpoiRbFtOrk5bW06uTlsAAAIARQAAAkACvAANABcAADMRITIWFhUVFAYGIyMR' +
  'ETMyNjU1NCYjI0UBG0JkOjtlQKKWND8+NZYCvDRfQQ5AYDT++gFzODEKMTgAAwA0/1ECbgLKAA0AGwAmAAAFIiY1NTQ2MzIWFRUU' +
  'BicyNjU1NCYjIgYVFRQWEyImNTUzFRQzMxUBUYKbm4KDmpqDTldXTk1XV3ouOXQcPQ6RiKaIkZGIpoiRbFtOrk5bW06uTlv+8zkw' +
  'RjQeXQACAEUAAAJLArwAFgAgAAAzESEyFhYVFRQGBxUWFhUVIzU0JiMjEREzMjY1NTQmIyNFAStCYjc+LCcteBsexqY0Ozo1pgK8' +
  'LlM6C0FOEhACMirn1hkf/vIBezcuCS83AAABACX/8gI8AsoANAAABSImJjU1MxUUFjMyNjU0JiYnJy4CNTQ2NjMyFhYVFSM1NCYm' +
  'IyIGFRQWFhcXHgIVFAYGATZQe0Z3VEZHSCJBLh5FZTY8bkpKdEN3Ij4qPkAdOSseSGw9QXUOOWxOGhpFRDouHycYCwYQMU4/P1ow' +
  'MmRLISErNBgwLBwnGQkHEDFQQD9gNgAAAQAZAAACMwK8AAcAADMRIzUhFSMR6tECGtECT21t/bEAAAEAQf/yAl0CvAATAAAFIiYm' +
  'NREzERQWMzI2NREzERQGBgFPVHlBeE5ISU14QHoOPXRQAcn+NEZMTEYBzP43UHQ9AAEAFAAAAlcCvAAHAAAzAzMTMxMzA866fJ4O' +
  'n3y7Arz9kQJv/UQAAQAgAAADXQK8AA8AADMDMxMzEzMTMxMzAyMDIwOBYXdMEWLRYhFLeGLRYxFkArz9lwJp/ZcCaf1EAnX9iwAB' +
  'ABgAAAJqArwADQAAMxMDMxMzEzMDEyMDIwMY09CJlRGUitDSiZcRlwFhAVv++gEG/qX+nwEM/vQAAQAJAAACYwK8AAkAADM1AzMT' +
  'MxMzAxX68YeeEZ6G8fcBxf7LATX+O/cAAQAvAAACFAK8AAsAADM1ATUhNSEVARUhFS8BZf6lAdf+mwFpmgGoDmya/lgObAAAAgAp' +
  '//ICKwH8ACYAMQAAFyImJjU0NjYzMzU0JiMiBgcnPgIzMhYVFRQzMxUjIiY1NSMOAicyNjU1IyIGFRQW4jRUMTFWN48wMzIzCGoM' +
  'NVhAYW8cKlEkLhEGHj0hOUiIJS4wDiVGMzJEIx4nMS8lIydAJ2Fcwh5fJB8CDigdXkE3CiAfHiUAAAIASf/yAk4CvAAWACQAAAUi' +
  'JicjFSMRMxEzPgIzMhYWFRUUBgYnMjY1NTQmIyIGFRUUFgFtRksREXFzEQsnPy89Zj4+Z14+UlE/PlNTDjEeQQK8/vQUIhY7clAQ' +
  'UHI7ZFFLCkxQUEwKS1EAAAEAMf/yAiYB/AAiAAAFIiYmNTU0NjYzMhYWFwcuAiMiBgYVFRQWFjMyNjcXDgIBMEh0Q0N0SEdlPglv' +
  'BB43KClBJSVBKT0/CG8MPmUOPHJQDlByPDJXNhcfMx4jRjEKMUUkPzIaNFYzAAACADH/8gI2ArwAFgAkAAAFIiYmNTU0NjYzMhYW' +
  'FzMRMxEjNSMGBicyNjU1NCYjIgYVFRQWARM8aD4+Zz0uQCcLEXJwERJKJD5SUT8+U1MOO3JQEFByOxYiFAEM/URBHjFkUUsKTFBQ' +
  'TApLUQACADH/8gIYAfwAGQAgAAAFIiYmNTU0NjYzMhYWFRUhFhYzMjY3Fw4CAzMmJiMiBgErSnE/PnBJSGw8/o0CTjk4Ng5fDjVY' +
  'yP0EQzU3Qg4/c00MTnI/P3JMKTpGMR8xGz0rATsxOjoAAAEAGwAAAZkCvAASAAAzESM1MzU0NjMzFSMiFRUzFSMRn4SEOS+AWhyI' +
  'iAGPX2QxOV8eUV/+cQAAAgAx/zgCNgH8AB0AKwAANzU0NjYzMhYXMzUzERQGIyE1ITI1NSMOAiMiJiYFMjY1NTQmIyIGFRUUFjE+' +
  'aD5GSRERcDgw/rQBJR0RCyY+Lz5oPgEEPlJRPz5TU/UPTm87Mh1B/bQxOWQejxEjGDtvRU9HCkhOTkgKR08AAAEASQAAAiMCvAAW' +
  'AAAzETMRMz4CMzIWFhURIxE0JiMiBhUVSXMRCCQ7LTlYMXM7Nj1GArz+8REiFjNcP/7YAR88O1FL+v//ADYAAADOAsMCJgDZAAAA' +
  'BgDSCwD////s/zgA0ALDAiYA2gAAAAYA0g0AAAEASQAAAh4CvAAMAAAzETMRMzczBxcjJyMVSXMRspfv95W8EQK8/ne77//JyQAB' +
  'AEkAAAC8ArwAAwAAMxEzEUlzArz9RAABAEkAAAMTAfcAJQAAMxEzFTM2NjMyFhczNjYzMhYWFREjETQmIyIGFREjETQmIyIGFRFJ' +
  'cRENPTM2QhEQEUA7Lkstcy4pLTVyLikuNAHuNxknLCIiLChOOv65AT8rLTs3/tsBPystOzf+2wABAEkAAAIjAfcAFQAAMxEzFTM2' +
  'NjMyFhYVESMRNCYjIgYVFUlxEQ1ERTlYMXM7Nj1GAe5FHDI0XD/+2AEfPDtRS/oAAAIAMf/yAjQB/AARAB8AAAUiJiY1NTQ2NjMy' +
  'FhYVFRQGBicyNjU1NCYjIgYVFRQWATNKdUNDdUpKdENDdEo/UFA/P1BQDj1xTxBPcjw8ck8QT3E9ZlFJCklRUUkKSVEAAAIASf84' +
  'Ak4B/AAWACQAABcRMxUzNjYzMhYWFRUUBgYjIiYmJyMREzI2NTU0JiMiBhUVFBZJcRERS0Y8Zz4+Zj0vPycLEY8/UVI+PlNTyAK2' +
  'QR8wO3JQEFByOxYkEv76AR5RSwpMUFBMCktRAAIAMf84AjYB/AAWACQAAAURIw4CIyImJjU1NDY2MzIWFzM1MxEBMjY1NTQmIyIG' +
  'FRUUFgHEEQsnQC49Zz4+aDxGShIRcP7/P1FSPj5TU8gBBhIkFjtyUBBQcjswH0H9SgEeUUsKTFBQTApLUQAAAQBJAAABagHwAA4A' +
  'ADMRMxUzNjYzMxUjIgYVEUlxEQs0JDw+Mj4B7jkfHGY1N/7iAAABACz/8gHiAfwAKgAABSImJzceAjMyNjU0JicnLgI1NDYzMhYX' +
  'ByYmIyIGFRQWFxceAhUUBgEVYHwNagckNR8vLy0uHzNUM2tXU2wQagg2JygrLCUfN1k0bw5UURsmLBIiGhsaCQUKIz0vSE5KPiAq' +
  'IxwaGhoGBgogPDNNUwABABsAAAGdAo0AEgAAISImNREjNTM1MxUzFSMRFDMzFQEFMDmBgXOOjhxjOTEBJV+fn1/+7h5fAAEARf/4' +
  'Ah4B7gAVAAAFIiYmNREzERQWMzI2NTUzESM1IwYGAQY5WDByOzY9R3JwEQ1FCDNdPgEo/uE8OlBL+v4SRRsyAAABABQAAAIOAe4A' +
  'BwAAMwMzEzMTMwO2onp6EXt6ogHu/mYBmv4SAAEAKwAAAukB7gAPAAAzAzMTMxMzEzMTMwMjAyMDeE1yNRFLuEsRNXJNv0oRSwHu' +
  '/l8Bof5fAaH+EgGh/l8AAQAeAAACMgHuAA0AADM3JzMXMzczBxcjJyMHHri1hnkReYW1uId6EXr59aur9fmurgABAEX/OAIeAe4A' +
  'HQAAFzUhMjU1Iw4CIyImJjURMxEUFjMyNjU1MxEUBiOAAREcEQgkPC45WDByOzY9R3I4MMhkHooSIxczXT4BKP7hPDpQS/r9tDE5' +
  'AAEANgAAAdQB7gALAAAzNSU1ITUhFQUVIRU2ARr+8AGM/uYBIor2D1+K9g9fAAACADT/8gJSAsoADQAbAAAFIiY1NTQ2MzIWFRUU' +
  'BicyNjU1NCYjIgYVFRQWAUN7lJR7fJOTfE9LUkhKUE0OiouuiI2NiK6LimhYUbdSVlhQt1NWAAABAA0AAAF2ArwABwAAIREjByMT' +
  'MxEBAhFpe5XUAmjlATn9RAABAC0AAAIrAsoAKQAAMzU0NjY3Nz4CNTU0JiMiBhUVIzU0NjYzMhYWFRUUBgYHBw4CFRUhFS0xXEJA' +
  'JzYeSj4+TnREdEhIc0E2Xzw+LTUWAYFRSl89FBQNJDUkBDY/Q0ERD0xqODdiQgpDXDsTEw4gKR8HaAAAAQAl//ICNAK8ACUAAAUi' +
  'JiY1NTMVFBYzMjY1NTQmJiMjNTc1ITUhFQcVMzIWFhUVFAYGATBOeUR0U0RETCM7JYbt/pIB7uApMls6QXUOOGlJEg89SEMzCSQs' +
  'FYKFD2icfg8nUEALRGQ3AAIAGwAAAmICvAAKAA8AACE1ITUTMxEzFSMVJTMRIwMBef6i/9N1df6e7hHdjocBp/46aI72AXz+kwAB' +
  'ACn/8gIyArwAKAAABSImJjU1MxUUFjMyNjU1NCYjIgYGByMRIRUhFTM+AjMyFhYVFRQGBgEvUXVAdklFRUxLOSApGgiQAdn+mxEL' +
  'IzkoPmU8PnQOOmpGCgk5Skw+CT1IEhsOAYVqvA8bEzVmSgtJbDwAAAIANP/yAj4CygAhADEAAAUiJiY1NTQ2NjMyFhYVIzQmIyIG' +
  'FRUzNjYzMhYWFRUUBgYnMjY1NTQmJiMiBgYVFRQWATdOdEFEd05OcT12P0dHTRERSkQ+Z0BCdk1CTiNBLCtCI04OO2pG8VNwOTVh' +
  'Qi5CS0JOFyc0ZEYMRmk6aEc7CCk6ISE6KQg7RwAAAQAcAAACEwK8AA8AADM1NDY3EzUhNSEVAQYGFRWIDBTy/oIB9/8ADQkaJjUj' +
  'Aa0PaIr+NxcjGhUAAAMAIf/yAj0CygAlADMAQQAABSImJjU1NDY2NzUuAjU1NDY2MzIWFhUVFAYGBxUeAhUVFAYGJzI2NTU0JiMi' +
  'BhUVFBYTMjY1NTQmIyIGFRUUFgEvUXpDJDYYGDEfQXVOTXVBHy8ZGTUkRHpQSVFQSkpQUUlES01CQk1LDjBbPQwxQCQHEQgkPCsM' +
  'N1MuLlM3DCs8JAgRByRAMQw9WzBoODEIMDk5MAgxOAFBMi4ILTIyLQguMgAAAgAr//ICNALKACEAMQAABSImJjUzFBYzMjY1NSMG' +
  'BiMiJiY1NTQ2NjMyFhYVFRQGBgMyNjY1NTQmIyIGFRUUFhYBLE5xPnZBRkdNERJIRj1oP0J2Tk51QEN3Sy1AJE5DQk4kQQ41YUIu' +
  'QktCThcnNGRGDEdoOjtqRvFTcDkBYiE7KAg8RkY8CCg7IQABAEn/DQFQAvEAEQAAFyImNRE0NjMzFSMiFREUMzMVqSo2NiqnfRsb' +
  'ffM2KgMkKjZiHv0cHmIAAAEAEf8NARcC8QARAAAXNTMyNRE0IyM1MzIWFREUBiMRfBsbfKYrNTUr82IeAuQeYjYq/NwqNgAAAQAl' +
  '/w0BuQLxACMAAAUiJjURNCMjNTMyNRE0NjMzFSMiFREUBiMjFTMyFhURFDMzFQESKjYhbGwhNiqnfRsqIw4OIyobffM2KgE5Im4i' +
  'ATkqNmIe/uYiLhAuIv7mHmIAAQAR/w0BpQLxACMAABc1MzI1ETQ2MzM1IyImNRE0IyM1MzIWFREUMzMVIyIVERQGIxF8GyokDQ0k' +
  'Kht8pio2ImxsIjYq82IeARoiLhAuIgEaHmI2Kv7HIm4i/scqNgAAAQA0/w0BgQLxABEAAAUiJiY1ETQ2NjMVIgYVERQWMwGBbJRN' +
  'TZRscG5ucPNLnXkBInqcS2J+hv7ohX8AAQAC/w0BTgLxABEAABc1MjY1ETQmIzUyFhYVERQGBgJwbW1wbJRMTJTzYn+FARiGfmJL' +
  'nHr+3nmdSwAAAf/0/zgBjAK8AAMAAAcBMwEMASZy/trIA4T8fAAAAQBF/woAuAMmAAMAABcRMxFFc/YEHPvkAAACAEX/CgC4AyYA' +
  'AwAHAAATETMRAxEzEUVzc3MBbgG4/kj9nAG4/kgAAf/z/zgBjAK8AAMAAAUBMwEBGf7acwEmyAOE/Hz//wA3AZsA5ALKAgcAUgAA' +
  'Ain//wA3AZsBtALKACcAUgAAAikABwBSANACKf//ADgBmwDlAsoADwBSARwCPMAA//8ANwGbAOQCygIHAFIAAAIp//8AOAGbAbUC' +
  'ygAvAFIB7AI8wAAADwBSARwCPMAA//8ANwGbAbQCygAnAFIAAAIpAAcAUgDQAin//wA3/3IA5AChAgYAUgAAAAEAN//yAOgAowAL' +
  'AAAXIiY1NDYzMhYVFAaQJjMzJiYyMg4yJyYyMicnMQAAAQA3/3IA5AChABIAABc1MzI1NSMiJjU0NjMyFhUVFCNOJSsQJTIyJSYw' +
  'aY5AKyAtIyUvMCduav//ADf/8gDoAf0CJgBRAAAABwBRAAABWv//ADf/cgDoAf0CJwBRAAABWgAGAFICAP//ADf/8gLKAKMAJgBR' +
  'AAAAJwBRAPEAAAAHAFEB4gAAAAIAN//yAOgCvAADAA8AADcRMxEHIiY1NDYzMhYVFAZVdTomMzMmJjIy3AHg/iDqMicmMjInJzEA' +
  'AgA3/zgA6AH8AAMADwAAFxEzEQMyFhUUBiMiJjU0NlV1OiYyMiYmMzPIAdv+JQLEMScnMTEnJzEAAAIAJP/yAhcCygAkADAAADc1' +
  'NDY3NzY2NTQmJiMiBgYVFSM1NDY2MzIWFhUUBgYHBwYGFRUHIiY1NDYzMhYVFAbYJy4TLzIgOSUnPSV2Q3RIR24/K0QkFBIOOSUz' +
  'MyUmMzPcIDI/FQkWMysgLRgaMycaGEVjNDRbPDtMMBEJCBgWHOoxJycyMicnMQAAAgAr/yoCHgH8ACQAMAAABSImJjU0NjY3NzY2' +
  'NTUzFRQGBwcGBhUUFhYzMjY2NTUzFRQGBgMyFhUUBiMiJjU0NgEgR28/LEMkFBIPeCcuFC4zIDolJj4kdkNzPSYzMyYlMzPWM1w7' +
  'O00wEQkIFxcXHDI+FgkVMi0gLRcZNCcZGERiNQLSMScnMTEnJzEAAAEARwDMAW8BMwADAAA3NSEVRwEozGdnAAEARwDMAgcBMwAD' +
  'AAA3NSEVRwHAzGdnAAEARwDMAzcBMwADAAA3NSEVRwLwzGdn//8AEQDGAMIBdwAHAFH/2gDUAAEARP9oAij/0AADAAAXNSEVRAHk' +
  'mGhoAAIARf84A7gCyABFAFMAAAUiJiY1NTQ2NjMzMhYWFRUUBiMjIiY1NSMOAiMiJiY1NTQ2NjMyFhYXMzUzERQWMzMyNjU1NCYm' +
  'IyMiBgYVFRQWFjMzFQMyNjU1NCYjIgYVFRQWAg6NzW9sx4kVfrxoV1Y0LjARCCAyKD5bMjBYOyczHwoRbg4QBiQfRYlmD2eWUVSe' +
  'bc3kNEBANDU+Pshsx4oXisdraLx+QG93Jh8EFSUWQnBFEEZwQhQgEj7+lhEPPkM9Y41MTplwEHGaTmgBI1FGDEZRUUYMRlEAAgAg' +
  'AAACQgK8ACIAKwAAMyImJjU0NjY3NSYmNTQ2NjMzFSMiBhUUFhYzMzUzFTMVIxEnMzUjIgYVFBbvPV01IDYgMUA2XTtxXTBAHzMe' +
  'a3JeXuFvbzBAQy1UOytBKgoND0o/PFQrXzMzIy0WX19f/s5f0zU0NjQAAQAtAP4B6gK8AC8AABM1Mxc3Jyc3Fxc3JzUzFQcXNzcX' +
  'BwcXNzMVIycHFxcHJycHFxUjNTcnBwcnNzcnBy1PSAU7ODA5KQ0MRQwNKTkxOTsFSE9PSAU7OTE5KQ0MRQwNKTkwODsFSAG7RQwM' +
  'KjkwODsFR1BQRwU7ODA5KgwMRQwNKTkxODsFR1BQRwU7ODE5KQ0M//8AFAAAAmUDdwImAAIAAAAHANYAjgAA//8AFAAAAmUDdgIm' +
  'AAIAAAAHAMoAyAAA//8AFAAAAmUDdgImAAIAAAAGAM9VAP//ABQAAAJlA3kCJgACAAAABgDoYAD//wAUAAACZQOJAiYAAgAAAAYA' +
  '0VkA//8AFAAAAmUDsgImAAIAAAAHAOAAqgAAAAIAFAAAAxQCvAALABUAACERIRUhFSEVIRUhFSETMxUjAzMVIwcBegGU/uMBAf7/' +
  'ASP9APZwEH+PszgCvG24bb1tArxA/pJuoAD//wA0/ywCVwLKAiYABAAAAAcAzQCwAAD//wAuAAACawK8AiYABQAAAAYA5O8A//8A' +
  'RQAAAggDdwImAAYAAAAGANZ7AP//AEUAAAIIA3YCJgAGAAAABwDKALUAAP//AEUAAAIIA3YCJgAGAAAABgDPQgD//wBFAAACCAOJ' +
  'AiYABgAAAAYA0UYA//8ANP/yAlYDdgImAAgAAAAHAMwAgwAA/////gAAAMoDdwImAAoAAAAGANbTAP//ADgAAAEEA3YCJgAKAAAA' +
  'BgDKDQD////FAAABPQN2AiYACgAAAAYAz5oA////yQAAATkDiQImAAoAAAAGANGeAP//ADUAAADNA4oCJgAKAAAABgDTCgD//wBF' +
  'AAACVwN5AiYADwAAAAYA6HEA//8ANP/yAm4DdwImABAAAAAHANYAowAA//8ANP/yAm4DdgImABAAAAAHAMoA3QAA//8ANP/yAm4D' +
  'dgImABAAAAAGAM9qAP//ADT/8gJuA3kCJgAQAAAABgDodAD//wA0//ICbgOJAiYAEAAAAAYA0W4A//8ANP+lAm4DCwImABAAAAAG' +
  'AOFVAP//ACX/LAI8AsoCJgAUAAAABwDNAKEAAP//AEH/8gJdA3cCJgAWAAAABwDWAKEAAP//AEH/8gJdA3YCJgAWAAAABwDKANsA' +
  'AP//AEH/8gJdA3YCJgAWAAAABgDPaAD//wBB//ICXQOJAiYAFgAAAAYA0WwA//8ACQAAAmMDdgImABoAAAAHAMoAwgAAAAIARQAA' +
  'AkACvAAVABkAADc1MzI2NTU0JiMjNTMyFhYVFRQGBiMFETMRvpY0Pz41lqJCZDo7ZUD+5XmNbjgwCjE4bTRfQQ1BYDSNArz9RAD/' +
  '/wAp//ICKwK8AiYAHAAAAAYA1WcA//8AKf/yAisCugImABwAAAAHAMYApwAA//8AKf/yAisCugImABwAAAAGAM4zAP//ACn/8gIr' +
  'ArACJgAcAAAABgDnPgD//wAp//ICKwK/AiYAHAAAAAYA0D0A//8AKf/yAisC4gImABwAAAAHAN8AhwAAAAQAKf/yA0kB/AAYACMA' +
  'QQBIAAAFIiYmNTQ2NjMyFhYVFSEWFjMyNjcXDgIlMjY1NSMiBhUUFhciJjU0NjMzNTQmIyIGByc+AjMyFhczBxcjDgITMyYmIyIG' +
  'AnFIazs7Z0NIZDX+oQNGODY4DlYTNUz+UTlHhykwMiJWb21VjzYzMjcLZg42WD4+TRgaFgobCipKwu0BPzQ2QA5HeUlJdERAbkU4' +
  'NkUvGTwcNCBdQzcIIB4fJV1RS01MICYyMCQjJ0AnKSGvshIsIQE1NTw9AP//ADH/LAImAfwCJgAeAAAABwDNAJUAAAADADH/8QI2' +
  'AwYAGAAnACsAAAUGJiY1NTQ2Njc2FhczJiYnNx4CFRQGBicyNjY1NTQmIyIGFRUUFhMnNxcBNE11QT5nPjRGGBEUf2Qkb5ZNQXRO' +
  'KkAlUD8/UFAoNpE3DgFAdEwKS28+AQEjHE91IlwkiL1zYoRDZSVGMQVKUlJKBUlTAb0pyCn//wAx//ICGAK8AiYAIAAAAAYA1XUA' +
  '//8AMf/yAhgCugImACAAAAAHAMYAtgAA//8AMf/yAhgCugImACAAAAAGAM5BAP//ADH/8gIYAr8CJgAgAAAABgDQTAD//wAx/zgC' +
  'NgK6AiYAIgAAAAYAy3wA////+wAAAMkCvAImANkAAAAGANXQAP//ADwAAAEKAroCJgDZAAAABgDGEQD////HAAABPgK6AiYA2QAA' +
  'AAYAzpwA////0QAAATICvwImANkAAAAGANCmAP//AEkAAAIjArACJgApAAAABgDnVQD//wAx//ICNAK8AiYAKgAAAAcA1QCAAAD/' +
  '/wAx//ICNAK6AiYAKgAAAAcAxgDBAAD//wAx//ICNAK6AiYAKgAAAAYAzkwA//8AMf/yAjQCsAImACoAAAAGAOdXAP//ADH/8gI0' +
  'Ar8CJgAqAAAABgDQVwD//wAx/7sCNAIuAiYAKgAAAAYA4isA//8ALP8sAeIB/AImAC4AAAAGAM1vAAABAEn/8gJsAsoAPAAABSIm' +
  'Jic3FhYzMjY1NCYmJycmJjU0Njc2NjU0JiMiBgYVESMRNDY2MzIWFhUUBgYHBgYVFBcXHgIVFAYGAaY+VzIIZwkzLCgtFSYZKSoo' +
  'IiAaKTcrIkUtckN2TT1gNh8yHAoKGxwqQycwWA4qQyQgJy0rIhYeFQkPEDEfIywWES8hICYiT0P+SwGxWX5CKksvKz0rEgUMBxAK' +
  'Cw8qPzExTCwA//8ARf/4Ah4CvAImADAAAAAGANV/AP//AEX/+AIeAroCJgAwAAAABwDGAMAAAP//AEX/+AIeAroCJgAwAAAABgDO' +
  'SwD//wBF//gCHgK/AiYAMAAAAAYA0FUA//8ARf84Ah4CugImADQAAAAHAMYAwAAA//8ARf84Ah4CvwImADQAAAAGANBVAAACAEn/' +
  'OAJOArwAFwAlAAAXETMRMz4CMzIWFhUVFAYGIyImJicjERMyNjU1NCYjIgYVFRQWSXIRDCZALj1nPj5nPS5AJgwRkD9RUT8+U1PI' +
  'A4T+9BQiFjtyUBBQcjsWIxP++gEeUUsKTFBQTApLUQAAAgAjAVQBjwLFACIALQAAEyImNTQ2MzM1NCYjIgYHJzY2MzIWFRUUMzMV' +
  'IyImJyMOAicyNjU1IyIGFRQWpDdKSzlfHiMhIwZLC0tCQlETIT0aHwIMBBcqEycsVxgfIAFUODc1OBEdIyEWGSg6Q0SIFUMYFgoa' +
  'FEUmKAsYExUZAAACACIBVAGTAsUACwAXAAATIiY1NDYzMhYVFAYnMjY1NCYjIgYVFBbaU2VlU1NmZlMtNTUtLDY2AVRhWFhgYFhY' +
  'YUY7ODc7Ozc4OwAAAgAh//IBtQLKADcASAAAFyImNTUzFRQWMzI2NTQmJyYmNTQ2NyY1NTQ2NjMyFhUVIzU0JiYjIgYVFBYXFhYV' +
  'FAcWFhUVFAYDNjY1NCYnJiYnBhUUFhcWFvRicWQ2OC4uLDlVXgwLFzBRM1ZsYxQpHyUsPTBYUxQKCWMHAgErOBMkEQQ7MBUdDmxa' +
  'EA0xOiUiISMLD0xGGCkRIi0GMUYlWE0YDxclFCAeJCAJEE1BMiQQJhUISl4BPQMHBhwjCgMLBggNIB4JBAcAAAIAEwAAAhcCvAAR' +
  'ABsAACERIyImJjU1NDY2MyERIxEjEQMzNSMiBhUVFBYBABc/YTY4Yz8BKmNRfxwcMjw+ASE0WTsLPFoy/UQCXv2iAX/fOzEGMTwA' +
  'AwA0//QCmALIABMAIwBDAAAFIiYmNTU0NjYzMzIWFhUVFAYGIyczMjY1NTQmIyMiBhUVFBY3IiY1NTQ2MzIWFRUjNTQmIyIGFRUU' +
  'FjMyNjU1MxUUBgFdWoZJSYZaEluFSUmFWxAPYWtrYQ9iampsQU1NQUZEWBcbGRscGBkZWEMMR4dhdmGHR0eHYXZhh0dYbGp4amxs' +
  'anhqbElOSmNKT04/DxUXHR0ZgxkcHBkUDz9OAAQAMgEqAdYCygAPABsALwA4AAABIiYmNTQ2NjMyFhYVFAYGJzI2NTQmIyIGFRQW' +
  'NzUzMhYVFAYHFRYWFRUjNTQjIxU1MzI2NTQmIyMBBDxfNzdfPDxfNzdfPEtcXEtLXFwDVSUmExURDykVMSwRERERLAEqNV49PV41' +
  'NV49PV41KVtMS1xbTEtcOt4kGBQcCAoBFBA7PBVRdxQNDhMAAgApAAACUQK8ABsAHwAAMzUjNTM1IzUzNTMVMzUzFTMVIxUzFSMV' +
  'IzUjFREzNSOZcHBwcGh4aHBwcHBoeHh4v2J6Yr+/v79iemK/v78BIXoAAAIAKQBRAkMCawAjADMAADcnNyYmNTQ2Nyc3FzY2MzIW' +
  'FzcXBxYWFRQGBxcHJwYGIyImJzcyNjY1NCYmIyIGBhUUFhZwRz0VFRUVPUc9HUUnJkYdPUc9FBYWFD1HPR1GJidFHYkqRCkpRCoq' +
  'RCkpRFFHPR1FJyZGHT1HPRQWFhQ9Rz0dRiYnRR09Rz0VFRUVOShEKytEKChEKypFKAAAAgAl/4wCPAMwADQAOAAABSImJjU1MxUU' +
  'FjMyNjU0JiYnJy4CNTQ2NjMyFhYVFSM1NCYmIyIGFRQWFhcXHgIVFAYGBxEzEQE2UHtGd1RGR0ghQC4eRWU3PW5KSnRCdiI+Kj8/' +
  'HTkrHkhqPUF1h20OOWxOGhpFRDouHycYCwYQMU4/P1owMmRLISErNBgwLBwnGQkHEDFQQD9gNmYDpPxcAAEANgAAAkUCygAdAAAz' +
  'NTM1IzUzNTQ2MzIWFRUjNTQmIyIGFRUzFSMVIRU2SkZGeWdoeHI7MzI7amoBUmi7Xm5oc3NoPUA1Ozs1cV67aAAAAwADAAACaQK8' +
  'AAsADwATAAAzEScDMxMzEzMDBxElNSEVJTUhFfoU44miEKKJ4xT+5wG6/kYBugEPCgGj/s0BM/5dCv7xdV1dlF5eAAIANP+MAioC' +
  'ZAAiACYAAAUiJiY1NTQ2NjMyFhYXBy4CIyIGBhUVFBYWMzI2NxcOAgcRMxEBNEh0RER0SEZlPgpvBR42KSlBJSVBKT0/CW8NPmV4' +
  'Zw48clAOUHI8Mlc2Fx8zHiNGMQoxRSQ/Mho0VjNmAtj9KAABABL/9gJvAsYAAwAAFycBF1A+Ah8+CjICnjIABQAc//MC3QLJAAMA' +
  'EQAfAC0AOwAAFycBFwMiJjU1NDYzMhYVFRQGJzI2NTU0JiMiBhUVFBYBIiY1NTQ2MzIWFRUUBicyNjU1NCYjIgYVFRQWkUcCH0Zz' +
  'S1ZWS0pXVksgJSUgICUl/qFLVlZLSlhWTCElJSEgJSUNOAKeOP1kUkcHR1JSRwdHUkwpIA8hKCghDyApAU1SRgdIUlJIB0ZSTCgh' +
  'DyApKSAPISgA//8AEf/2AyoCxgAmAN4AAAAmALE6AAAHANQBtAAA//8AEf/2AxsCxgAmAN4AAAAmALE6AAAHAOkBywAA//8AFv/2' +
  'A2sCxgAmAOYAAAAmALF7AAAHANQB9QAAAAEAZQCNAgcCLwALAAAlNSM1MzUzFTMVIxUBAJubbJubjZ1onZ1onQABAGQAjQIIAi8A' +
  'CwAANyc3JzcXNxcHFwcnrkqIiEqIiEqIiEqIjUqHh0qHh0qHh0qHAAMAZQBVAgcCZwADAA8AGwAAEzUhFQciJjU0NjMyFhUUBgMi' +
  'JjU0NjMyFhUUBmUBotEiLy8iIi8vIiIvLyIiLy8BKmho1S8hIi8vIiEvAXEvIiEvLyEiLwACAGUA1gIHAeYAAwAHAAATNSEVBTUh' +
  'FWUBov5eAaIBfmhoqGhoAAEAZACCAggCOgAHAAAlJTUlFQUVBQII/lwBpP7MATSClY6Vb2UQZQABAGQAggIIAjoABwAANzUlNSU1' +
  'BRVkATT+zAGkgm9lEGVvlY4AAAIAZQAAAgcCHwALAA8AACU1IzUzNTMVMxUjFQU1IRUBAJubbJub/vkBop+MaIyMaIyfaGgAAAEA' +
  'RwGoAiUCvAAHAAATEzMTIycjB0eZrJmBZhBmAagBFP7sysoAAQA1APUCNgHHAB0AADcnNzY2MzIWFxYWMzI2NzcXBwYGIyImJyYm' +
  'IyIGB3VAcRQrHB0lDg0QDQwUC1BAcRMsHB0lDg0PDgwTDPVUVhAVGRMTEAwJPVRWDxYZExQPDAkAAQBkAK8CCAGSAAUAACU1ITUh' +
  'FQGi/sIBpK97aOMAAgAhAY0BZgLKAA8AGwAAEyImJjU0NjYzMhYWFRQGBicyNjU0JiMiBhUUFsMtSisrSi0uSisrSi4fJycfHigo' +
  'AY0pSC4uSCgoSC4uSClZJx8fJiUgHycA//8AKwIrAPkCvAAGANUAAP//ACsCKQD5AroABgDGAAD//wArAikBjAK/AAYA0AAAAAEA' +
  'KwI4AW8ClAADAAATNSEVKwFEAjhcXAD//wAr/ywBGwAUAAYAzQAAAAEAKwIpAPkCugADAAATNzMHK0uDaAIpkZH//wARAV4A2QK8' +
  'AgcA3QAAAV7//wAaAV4BUALIAgcA6QAAAV7//wAWAVIBUgK8AgcA5QAAAV4AAQArAvYA9wN2AAMAABM3MwcrRoZkAvaAgAABACsC' +
  'JQFuAroAEQAAEyImNTUzFRQWMzI2NTUzFRQGzUxWYB8jIh9gVQIlTEMGBB4nJx4EBkNMAAEAKwLwAWwDdgARAAATIiY1NTMVFBYz' +
  'MjY1NTMVFAbMTFVeICMjH15VAvBHOwQEGSQkGQQEO0cAAQAr/ywBGwAUABcAABciJic3FhYzMjY1NCYjIzczBzIWFRQGBpwgOxYW' +
  'EioaFBsYGSYITwUnMyQ61A0JRQcLDhAODmU9KSgfKBMAAAEAKwIpAaICugAHAAATNzMXIycjByt3iXd2PRE9AimRkUxMAAEAKwL2' +
  'AaMDdgAHAAATNzMXIycjByt2jXV9NhE3AvaAgEREAAIAKwIpAYwCvwALABcAAAEiJjU0NjMyFhUUBiMiJjU0NjMyFhUUBgFBICws' +
  'ICEqKusgLCwgISsrAikpIiMoKCMiKSkiIygoIyIpAAACACsC8wGbA4kACwAXAAABIiY1NDYzMhYVFAYjIiY1NDYzMhYVFAYBTyAr' +
  'KyAhKyv5ICwsICErKwLzKSIjKCgjIikpIiMoKCMiKQAAAQArAi0AwwLDAAsAABMiJjU0NjMyFhUUBncfLS0fISsrAi0pIiIpKSIi' +
  'KQABACsC8wDDA4oACwAAEyImNTQ2MzIWFRQGdx8tLR8hKysC8yoiISoqISIqAAIAEwAAAXYBXgAKAA8AADM1IzU3MxUzFSMVJzM1' +
  'IwfgzY6VQEDGcA5iSlLCzkZKkJKGAAABACsCKwD5ArwAAwAAEyczF5Nog0sCK5GRAAEAKwL3APcDdwADAAATJzMXkGWHRQL3gIAA' +
  'AgA0AAkCgwHmAAkAEwAAJSU1JTMVBxUXFSElNSUzFQcVFxUCff7bASUGv7/+1v7bASUGv78JsH2we2sQa3ywfbB7axBrfAAAAgBE' +
  'AAkCkwHmAAkAEwAAJTU3NSc1MwUVBSE1NzUnNTMFFQUBaL+/BgEl/tv+1r+/BgEl/tsJfGsQa3uwfbB8axBre7B9sAAAAQBJAAAA' +
  'vAHuAAMAADMRMxFJcwHu/hIAAf/s/zgAvgHuAAoAAAc1MzI1ETMRFAYjFEMcczkwyGMeAjX9tDE5AAEARf84Al8B7gAeAAAXETMR' +
  'FBYzMjY1ETMRFDMzFSMiJic1IwYGIyImJyMVRXM7NT1CchwqUSQtAhENRTgjKw0RyAK2/uA5PExIAQH+jx5fJCIGIzETDN8AAAEA' +
  'EQAAANkBXgAHAAAzESMHIzczEYQNF08wmAETUZz+ov//ABEBXgDZArwCBwDdAAABXgACACsCHAD5AuIACwAXAAATIiY1NDYzMhYV' +
  'FAYnMjY1NCYjIgYVFBaSKzw8Kyw7PikQEREQDhMTAhw4Kys4OCstNkISDw4TEw4PEgAAAgArAuwA+QOyAAsAFwAAEyImNTQ2MzIW' +
  'FRQGJzI2NTQmIyIGFRQWkis8PCssOz4pEBEREA4TEwLsOCsrODcsLTZCEg8OExMODhMAAAEAK/+lAc8DCwADAAAXJwEXeE0BV01b' +
  'HwNHHwABACv/uwHkAi4AAwAAFycBF2xBAXhBRSoCSSr//wBHAMwBbwEzAgYAWgAAAAEAPwE0AYoBhwADAAATNSEVPwFLATRTUwAA' +
  'AQAW//QBUgFeAB0AABciJic3FhYzMjY1NCYjIzU3NSM1IRUHFRYWFRQGBrdCWgVVAyseICUlIkFetQEzbzU8KUYMQDsIHCEgFxkZ' +
  'PyoNRUo2DQIwMSQ3HwD//wAWAVIBUgK8AgcA5QAAAV4AAQArAh4BhgKwAB0AABMnNzY2MzIWFxYWMzI2NzcXBwYGIyImJyYmIyIG' +
  'B2xBIQ4pGRUhEAoVDA8RBxJAIA4oGhYgEQkUDg4RBwIfKDkZFxEQCRESCx0pOBgYEQ8KEBIKAAABACsC7AGOA3kAHQAAEyc3NjYz' +
  'MhYXFhYzMjY3NxcHBgYjIiYnJiYjIgYHZzwgESgbGB8RCxUODxMIEzwgECgbGB8SChUODxMJAu0uLRcaEA8KEBILGy8sFxoQDwkR' +
  'EwsAAAEAGgAAAVABagAcAAAzNTQ2NzY2NTQmIyIGByc2NjMyFhUUBgcGBgczFRpBRC8sJBwbKANWBVZBQlRKQCskAdgpOkQPCxwY' +
  'FhkcIgY+QEA2NjYOChYURgABAAAA6gBcAAgAZAAFAAEAAAAAAAAAAAAAAAAAAwACAAAAAAAAABoAWQCFAKkAvwDTAQoBIQEtAU8B' +
  'agF5AZYBrQHXAfwCMwJjAq0CvgLfAvIDEQMuA0MDWwOfA9UECgRABHQEkATOBPEE/AUHBR4FKgVgBYIFsgXoBh8GOAZ3BpMGtgbJ' +
  'BugHAQcsB0MHbQd/B7oH7wgMCEYIjAipCQQJSglmCYIJsgniCgAKHgotCjoKTgpdCmYKcwp9CoYKlQqiCqoKwArcCugK9AsECyAL' +
  'PQuDC8oL1gviC+4L9wwDDHAMrAz2DQINDg0ZDSQNLw07DWANbA13DYINjg2ZDaQNsA27DcYN0Q3cDecN8g3+DgoOFQ4gDisONg5C' +
  'Dk4OWg5lDnAOfA6kDq8Ouw7GDtEO3A7oD1APXA+gD6sPtw/CD80P2A/jD+4P+RAEEA8QGxAnEDIQPRBIEFMQXhC2EMEQzRDYEOMQ' +
  '7xD6ETIRchGYEf0SKBKBEtAS+RNIE5gTwBPmFCEULxSFFJQUoxSyFMYU3xULFR4VMhVFFWAVcxWjFbIV3hXmFe4V9hYDFgsWGBYh' +
  'FioWMxZAFlwWeBaeFrAWwhboFw4XJBc6F1QXYRduF5IXthfCF9YYAxgDGBQYHRhDGGkYdxiFGI0YmhjHGNAZARkyGV4AAAABAAAA' +
  'AgAA9Z+MGl8PPPUIAwPoAAAAANucIpkAAAAA5qcXJf+z/uMEzwRlAAAABgACAAAAAAAAA4MAXgD/AAACeQAUApcALgKDADQCmQAu' +
  'AiwARQIXAEUClQA0ApAARQEDAEUCXgAiAm4ARQIfAEUDbgBFApwARQKiADQCWwBFAqIANAJ4AEUCYAAlAkwAGQKfAEECagAUA3wA' +
  'IAKCABgCbQAJAkAALwJBACkCfwBJAk0AMQJ/ADECRQAxAbUAGwJ/ADECZwBJAQUANgEH/+wCLgBJAQUASQNXAEkCZwBJAmUAMQJ/' +
  'AEkCfwAxAYcASQINACwByQAbAmcARQIiABQDFAArAlAAHgJnAEUCBwA2AoYANAG8AA0CVAAtAl8AJQJ5ABsCWAApAmkANAIsABwC' +
  'XgAhAmkAKwFgAEkBYAARAcoAJQHKABEBiQA0AYMAAgGA//QA/QBFAP0ARQGA//MBHAA3AewANwEcADgBHAA3AewAOAHsADcBHAA3' +
  'AR8ANwEcADcBHwA3AR8ANwMBADcBHwA3AR8ANwJDACQCQwArAbYARwJOAEcDfgBHANIAEQJsAEQD+QBFAlIAIAIXAC0CeQAUAnkA' +
  'FAJ5ABQCeQAUAnkAFAJ5ABQDNwAUAoMANAKZAC4CLABFAiwARQIsAEUCLABFApUANAED//4BAwA4AQP/xQED/8kBAwA1ApwARQKi' +
  'ADQCogA0AqIANAKiADQCogA0AqIANAJgACUCnwBBAp8AQQKfAEECnwBBAm0ACQJbAEUCQQApAkEAKQJBACkCQQApAkEAKQJBACkD' +
  'dwApAk0AMQJoADECRQAxAkUAMQJFADECRQAxAn8AMQEF//sBBQA8AQX/xwEF/9ECZwBJAmUAMQJlADECZQAxAmUAMQJlADECZQAx' +
  'Ag0ALAKFAEkCZwBFAmcARQJnAEUCZwBFAmcARQJnAEUCfwBJAaMAIwG0ACIB4AAhAl0AEwLMADQCCAAyAnoAKQJsACkCYAAlAnwA' +
  'NgJsAAMCVgA0AoEAEgL5ABwDOgARAzgAEQN8ABYCbABlAmwAZAJsAGUCbABlAmwAZAJsAGQCbABlAmwARwJsADUCbABkAYcAIQEk' +
  'ACsBJAArAbgAKwGaACsBRwArAAAAKwEDABEBbQAaAW4AFgAAACsAAAArAAAAKwAAACsAAAArAAAAKwAAACsAAAArAAAAKwAAACsB' +
  'hwATAAAAKwAAACsCxwA0AscARAEFAEkBB//sAm8ARQD/AAABAwARAQMAEQAAACsAAAArAAAAKwAAACsBtgBHAckAPwFuABYBbgAW' +
  'AAAAKwAAACsBbQAaAAEAAAPY/twAAAT7/7P9OATPAAEAAAAAAAAAAAAAAAAAAADqAAQCNAJYAAUAAAKKAlgAAABLAooCWAAAAV4A' +
  'MgEjAAAAAAAAAAAAAAAAgAAABwAAAAAAAAAAAAAAAEZLAAAAwAAgICYD2P7cAAAEfgEkAAAAEQAAAAAB5gK8AAAAIAADAAAAAgAA' +
  'AAMAAAAUAAMAAQAAABQABAGkAAAAIAAgAAQAAAAvADkAQABaAGAAegB+AP8BHwExAV8gFCAaIB0gJv//AAAAIAAwADoAQQBbAGEA' +
  'ewCgAR4BMAFeIBMgGCAcICb//wAAAAYAAP/BAAD/uwAAAAAAAAAAAADgSAAA4DLgLwABACAAAAA8AAAARgAAAE4AVAESARQBFgAA' +
  'ARYAAAAAAAAAAQBWAEsAqwCtALIAYABKAEQARQBhALYAUgBaAFEARgBTAFQAugC5ALsAWABfAEAASQBBAL0AXgDBAEIARwBDAL4A' +
  '3ABXALAArgCsAK8ASACnAMMAqQClANcAvwDjAKoAxADAALwAyADJAMIA2wCoAF0AxQDHAKYA2ACzALQAtQBZAGIAYwBkAGUAZgBn' +
  'AGgAaQBrAGwAbQBuAHAAcQByAHMAagB1AHYAdwB4AHkAegC3AHsAfQB+AH8AgACBAIIAnQCDAIQAhQCGAIcAiACJAIoAjACNAI4A' +
  'jwCRAJIAkwCUAIsAlQCWAJcAmACZAJoAuACbAJ4AnwCgAKEAogCkAKMAbwCQAHQA2QB8AJwATABNAFAAAwAAAAAAAP+cADIAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAABAAH//wAPAAEAAAAMAAAAAAAAAAIADQACAAYAAQAIABAAAQATABYAAQAYABgAAQAaACAAAQAiACMA' +
  'AQAmACoAAQAtADAAAQAyADIAAQA0ADUAAQBoAGgAAQCJAIkAAQDZANkAAQAAAAEAAAAAABQAAABFAAAAAAAAAAAAAQAAAAwAAQAA' +
  'ABYAAQABAABAAEAAABMAAAABAADz+vz9/v8AAQIDBAUGCAkKCxYdAAQA6hAFBwcHBwQFBwYLCgoFCggIBwgGBAYHBgwICQYHBQMF' +
  'AgUFBwsLDAsFBwUFBQsFBQcIAgYHBQgNBAcJBgcEAQcMDA0NCwkKCwsKDxEPDxERDxAPEBASEBAFBQEBAQ0GAwMLBwcHBwcHBAcH' +
  'BAQEBAcLCwsLCwgICAgICAgEBwcHBwkHBwcHBwcHAAMGAgICAgULCwsLBwUFBQUFBQUMBwcHBwcHBQYGAQ4KAggGBAgGBgMDCgYF' +
  'BgYGBgYGBgYGBgkKCg0EBwYJBQMGBgYGBgYGBgYGBQYGDg4LCwcFCQkGBgYGAQkDAwYGBQAAAQABAAgAAQAAABQAAQAAABwAAndn' +
  'aHQBAAAAAAIAAQAAAAABBAK8AAAAAAABAAAAAAABAAPAAMAAAAAAAEAAQAAAAAABAAAAAQABAAAB6gDqAAAAAAHsAAAAAAAHABkA' +
  'SQBqAIkAmQCoANEA4ADpAQUBFwEjATgBSAFpAYEBrQHTAgkCFQIwAjwCUQJjAnQChQKyAtMC+AMcA0ADWgOBA54DpgOuA8EDygPy' +
  'BA8ELwROBHIEhgSxBMkE5gT1BQwFIAVEBVQFdQWDBbIF1AXpBhMGSAZfBpkGzgbiBvkHHAdCB1wHdgd/B4gHkwecB6QHrge3B78H' +
  'yQfTB9oH6Af9CAYIDggXCCgIOQhjCJUIoAirCLYIvwjICSAJSQmBCYkJkQmYCZ8JpwmvCcoJ0gnaCeIJ6gnyCfoKAQoJChEKGQoh' +
  'CikKMAo4CkAKRwpPClcKXwpnCm8Kdwp+CoYKjQqqCrIKugrCCsoK0graCx8LJwtUC1wLZAtsC3QLfAuEC4sLkwubC6MLqwuzC7sL' +
  'wwvLC9ML2wwZDCEMKQwxDDkMQQxJDHAMmwytDPoNGw1mDYYNpg3fDhcONQ5QDnIOfg6xDroOwg7JDtgO6g8FDw8PGw8nDzkPRQ9q' +
  'D3QPjA+TD5oPoQ+sD7MPvg/FD8wP0w/dD+4P/RAaECkQNxBPEGcQdhCIEJwQpxCyEM4Q6RDzEQIRJhEtEToRQRFTEWQRbxF6EYER' +
  'jBGtEbQR1xH8EhtAAIABAAgABQAAAIAA/4GDgAEACAAaAAAACv72CwP3+wYKCfgBgQABgYQG+voABgb4+IMAgAEACAA5AAAdHAEC' +
  'AgEBAgMBAgIEAQEBAgEBAgECAQIBAQIBAQIDgBv+AAIDAwMDBQQDAwQECgH8+Pj8AQoA+/f39wABAQr2gwT/AAEAAYIOCwsLAgP6' +
  '+gUFBf39+vUAgAEACAAlAAASEQEBAQEBAQUCBAEBAQEDAQEDBBH+/v7+/v4D9wQJCQkJ+/f3AwGBAf8BgQv+//b7Af8FCgYBAgAA' +
  'gAEACAA0AAAAgQH+/oETAwQDAwMDBAMKBP/39/f3/wQKAAGBgAMKCvb2ggD/gQABgQkLCwsHAAH59fX1gwCAAQAIAA8AAAcGAQIC' +
  'AgICAgb9AQgBCAL+gAP1BvsLgYABAAgADQAABgUBAgICAgIF/QEIAgj/gAL1BfuBAIABAAgALwAAGRgAAQIBAQEBAgEEAgMBAQEB' +
  'AwEBAgICAgIDGPz+/v7+/v4BBPj5BAkJCQn8+PgDBPj3+wGCAf8Bgw3/+Pb7Af8FCgT+/AYA/oGAAQAIAA4AAAYFAQICAgICBf0I' +
  '+AP4CIAABYEB+wCAAQAIAAkAAAAF/f0ICAAFgYeAAQAIAC4AAAAXAQD+/v4KCgoGAPr4+Pj4+AUFAwMDAQAEgYEMAQADAwAFDAwM' +
  'BAD19YEB9fWGAIABAAgAGgAAAA79/QgICfgGEwb3CQgIAASBggEHB4QB+fmEAIABAAgADgAAAAP9/QgIggD/gYIBCwuEAIABAAgA' +
  'IQAAABH9/RECA/MICPz8+wv5CQgIAASBggEJCYMB9vaBAfb2hIABAAgADwAABwYAAgEDAgEEBv0S+AXvCQKBAAmBAfcAgAEACAA5' +
  'AAAAHQH//v7+/v8BAgQEBAQCAf34+Pj4/QEFCQkJCQUAAoGCAf8BhAEB/4ENCgoF/wH79vb2+wH/BQqDgAEACAAZAAAMCwEBAgQD' +
  'AgEBBQEBAwv9AgMCAggIAff7AQGBCf/8+gAFBfn19QAAgAEACABPAAAAKAH//v7+/v8BAgQEBAQCAf34+Pj4/QEFCQkJCQUC//v7' +
  '+wcHBwcFBQACgYIB/wGEAQH/gREKCgX/Afv29vb7Af8FCvv7/wKBBAQEBAT7g4ABAAgAQgAAACD9/QICAgEBAQEDAwMEAwMD9/f3' +
  '+foICAgA+/X19fX7AAiDhAn/AP8BAQH///7+gQ/8+/r6+gAFBQUB/f759fX1gwCAAQAIAEIAACAfAQEBAQIBAgIDAwEBAQMEAwIC' +
  'AQIBAQECAQEBAQIBAgMf/v39/QgIAvz3+wL//fwAAfb2+f8BCAgGAwL7/gICAv6AHgEB/wH/CgoA+/r6+v4A/QD69/b2+f4DBAQG' +
  'BgMDAQCAAQAIAAoAAAQDAQICAgP6/wEGA/UA9QCAAQAIACwAAAAVAf/9/f39CQkJBAH9+fn5BQUFBAMAAYGBAgIDA4EGAggKCgoI' +
  'AoECAwMChACAAQAIAA8AAAAC9v4KgQL1AQqDggEICIaAAQAIACEAAAAR+f4KAgP5DAID/AcN+gMCDAAGgYIBCQmBAQkJgwH5+YSA' +
  'AQAIABsAAAAP/vj9CgAB+AQJBPcBAAoAAoGDAQkJhAH394SAAQAIABkAAAAL/Pz/CwEC+AUICAADgYAA+oEBCQmBAPqEgAEACAAZ' +
  'AAAACf//9PT//wICDQ2FgAMO9Pb2gQPyDAoKhIABAAgANgAAGhkCBgICAgIBAgMCAQICAwECAQEBAQMDAQIBAhn9//j8Agj+/gAD' +
  'AwMB+/v5+/3+AfgDCQkDAYAKAwH5+QAEAgIACQmBC//+AAEACPz8/gUIAIABAAgAJgAAEhEAAgICAgIBAwECAwQBAgMDAgMRAwkI' +
  '/QgJCQMCAgL79/f/CAj/gAH9+4EMBwUCAgIACgQB+AEEAIABAAgAKgAAFRQAAgEDAQQBAQEBBAIDAQMBAQEBAQMU//79/f4AAQL3' +
  '9wIICAb79/cCAQD9ghECAgICAf79+P8DBwoGBAEA/wAAgAEACAApAAAUEwECAwICAQEBAgICAQICAQIDAwIDE/z9/fz69/b19gL2' +
  '9fn79/f/CAj/gQUCAgIDBQeBCfv7AAoEAfgBBAAAgAEACAAqAAAUEwIEAgIBAgIBAgEBAQEBAwICAQECE/39/f///wkJ/vv39v7+' +
  'CfT+Agj8gBIBAgIA//0ECgoHBP8ABP74+P4AgAEACAAqAAAAFPn5///5+fn9/wEBBQUFBf//BQUA/4GABfn5AgL6/IIH9/f39wIC' +
  '+fmEAIABAAgALgAAFhUDAgIBAgIBAQECAwICAgIDAgICAwIDFf379vX2AgL+/Pz29fj7/fv39/8ICP8GAgIEBwIGBIEMCgr8/wEB' +
  'CgH9+AEFAIABAAgAMAAAABj9/QgICQkHBQQFBAMDA/j4+Pz/AggICAABgYIIBgYFAwICAgD/ggb/+/j4+PwChACAAQAIAAcAAACA' +
  'AgEABYGFgAEACAAHAAAAgAIBAAWBhYABAAgAHQAAAA79/QgICfsIEgj7CQgIAAaBggQGBgICAYEB/PyEgAEACAAJAAAABf39CAgA' +
  'BYGHgAEACAAvAAAXFgECAgMBAQECAQIBAQIBAQIBAgQCAQIDFv0ICQUDAwUDAQEBAfb29v3/BfkAAwj/FAIDAwEEBQUBAQIB/wD+' +
  '/Pj4APz4+IGAAQAIADAAAAAX/f0ICAkIBgQFBAMDA/j4+Pz/AggICAABgYAJAgIGBgQBAQEA/4IG//v4+Pj8AoQAgAEACAAkAAAR' +
  'EAEBBAICAgQBAgEDAgEBAwECEP/+/f//AgH/+vb2/wQICAT/gA//AgICAv8ACgT++Pj+BAoAAIABAAgAIwAAERABAgICAwMCAQQC' +
  'AgECAgQCAxD9CAkDAgICAwkI+/f3+wgI/wQCBwUCAoII+wAKBAH4AQQAgAEACAApAAAUEwEBAQEBAwEDAgICAgICAQICBAIDE/b1' +
  '9vf6/f39/Pn19gL79/f7CAj/A/v7/P+CDAICAgcCAAoEAfgBBAAAgAEACAAUAAAJCAACAgEBBAECAwj9CAkJCAYICAWABwIDAgL4' +
  '+PwAAIABAAgAMgAAGRgAAQEBAQUCAQEBAQMCAgEBAQEBAwEBBAUDGP/+/v4I/Pf3/P4B/f3//wEC9/cDCAj+Av+CFf0ACAL+/fz8' +
  '/QECAgIEAPz5/AAGAgAAgAEACAAZAAAMCwEBAQICAgICAQICAgv++vr/+gX/BQUFAv+ACAQG+QL9AvkJCYEAgAEACAAwAAAAF/38' +
  '/f39/QkJCQUC//j4+AQE+Pj3+PsAAYGBDQIDAgICAwcJCQkGAAICgQL8/P6EAIABAAgAFQAAAAn4/AgBAvoGCgACgYAFAgIICAIC' +
  'hIABAAgAJQAAABH2/Qj/APUH/P30/wb0/v0IAPyBgAkCAggIAgIICAICgQH6+oSAAQAIAB8AAAAN/Pj7B/8A+AUIBPcA/wiDgAcB' +
  'AgIICAICAYEB+fmEgAEACAA/AAAAH/z8+fn5+fj4+vz9/P39/f0JCQkFAv/4+PgEBAQA/gABgYAHCgoKCv39/v+CDwIDAgICAwcJ' +
  'CQkGAAICBgSFgAEACAAPAAAHBgEBAwIBAwIG/vT+AgwC/wQM+AL2CoGAAQAIACYAABIRAAIBAQUBAQEDAgEBAQICAQEDEQH+/v4E' +
  'BAQE/fn5+fwGCQkJAoAQ//8BAAH//wr/Av329gL/AwCAAQAIABIAAACBB/8K//kMDAAIgYAD9vb9/YYAgAEACABUAAAAK/39/fz7' +
  '+/78+PX19fX7/gIJCQn9/f39/v7+/wEBAQEAAQH/AQYJCQkBAQD+gYASAwIEBgYHBgUC/v769vb2+gD//4YN//7+/v39/fz9/gIH' +
  'CgqEAIABAAgAJwAAExIBAgMEAQIBBAIBAwIBAgEBAgEFEv/9CQD9+PgD/fL+AA0JBgQEBAGBEP8KCgEC+AL1APIA//8AAgEAgAEA' +
  'CAAWAAAKCQECAQICAgICAQIJ+f/yBQQF+fgJA4ACDQAKgQMK+AsAgAEACAAxAAAYFwIFAQECAQEBAgQBAgICAQEBAQECAgEBARf9' +
  'CQkD/fj4+PwICP0CCQoJCAUCAwQEBAOBFQcKCgUAAfb7/QD2BwcFAv//AAEA//8AgAEACABAAAAfHgACAQIBAQECAQECAQEBAwIB' +
  'AQICBAMCAQEDAwECAQIeAf3+/v7/AQEDBfn5/gEJCgoGBAQE/vn5+QEJCQkEAYAEAQH+AAGBFgEA/vr29v8FAv//AAEKAQH99v0B' +
  'BQoAAIABAAgAJAAAABH7+/v7+/T0/v7//wcHBgYGAP6BgQUBAwP19vaBAPKBAf//hACAAQAIAEYAACMiAQEBAgMCBgECAQEBBQID' +
  'AgECAgEBAQICAgEBAQICAgMCAQQJ/v37+/b1+/v9/4EWBAX////9+fPz8/oBBwcHAfn09AEGBvqCBAH/AP//gQX//wD/AAGBEAoH' +
  'AgL6+gICBwoF/fr2/f0AAIABAAgAQAAAHx4BAQECAQECAQMBAgEBBAECAQEBAgEBAQMBBQEEAQECgB3+/QkJA/349/j9/v79/QED' +
  'BAQEBAIA+/gBBAkGAwGADf8AAgYKCgb7/gEBAf//gQ3//wIA/wAHAvb2AgcKAACAAQAIABQAAAkIAAMBAwIDAQMDCAP9/QMGCAgG' +
  'Bgj9A/0D+fkHBwAAgAEACAAYAAALCgEDAQMCAQIBAgECCv/+/v8DBQkJBQMGCgcH+fkDA/0D/f0AAIABAAgAKAAAExIAAwECAgEC' +
  'AQMCAwEDAgEDAQMDAAaBAgb/BoEKBgkLCwoICgsLCQgS/QMA+wUFAP0D+fkBAf///wcHAACAAQAIACwAABUUAQMBAgECAQECAQMC' +
  'AwECAgECAQMCFP/+/v/+Af7//v7/AwkJAgkCCQkDCBQHB////wEBAQH5+QP9AAX7+wAD/QAAgAEACAAqAAAAEwUC/v7+/v7+AgUF' +
  'CAkJCQkIBQAFgRH9/QADBvr8AAMD+fn6+wUFBweDAIABAAgAKgAAABP+/vz7+/v7/P7+AgUGBgYGBQIAA4ER/QcHBQX7+vn5AwMA' +
  '/PoGAwD9gwCAAQAIAAkAAAAF/PwICAAEgYeAAQAIAAkAAAAF/f0ICAAFgYeAAQAIAA0AAAAJ/f0ICP39CAgABYGLgAEACAAJAAAA' +
  'Bf39CAgABIGHgAEACAAHAAAAgQAKgQDzg4ABAAgACgAAAIACDAAWgQHz84MAgAEACAAIAAAAAgoACoEA+4MAgAEACAAHAAAAgQAK' +
  'gQDzg4ABAAgACgAAAAMWCgAWgQH7+4MAgAEACAAKAAAAgAIMABaBAfPzgwCAAQAIAAUAAACBAAqBhIABAAgADAAABQQBAwEEBAQD' +
  '/wMMC4ADCg0HAACAAQAIABYAAAoJAQMDAwICAQECAgkBBgL/BQwMDAUKCf8CAgoNCgYB+wCAAQAIAAgAAACCAAuBgAD0gwCAAQAI' +
  'AAcAAACCAAuBAPSEgAEACAAIAAAAgAMJEgAdgYYAgAEACAAQAAAHBgECAgMBBASABQsD/wMMC4AFCgAKDQcAAIABAAgAEAAABwYB' +
  'AgUDAwECgAULDAP/AwsG9wD49P4CAACAAQAIADIAABgXAAEBAQEBAwMDAgIBAgMDAgIBAwIEAwIEF/n5+fv7+fX9Bgr+/v//AQAC' +
  'BQUA+QMG/xEKAgMGBwb/9vj+Av7/AP/9/v+BAwoNBwCAAQAIADwAAB0cAgECAgEBAQICAQEBAQEBAQMBAgECAgEDAgMCBAOAG///' +
  '//77+/oGBgYFBAcICwgC/vn2AgIAAwYA+f8cAQEDAwIBAQD3//76+vv7/gkKCgkC/wMAAvj0/gAAgAEACAAIAAADAgACAwL9/foC' +
  '+gUAAIABAAgACAAAAwIAAgMC/f36AvoFAACAAQAIAAgAAAMCAAIDAv39+gL6BQAAgAEACAAIAAAAAv4ACIEA+YMAgAEACAAGAAAC' +
  'AQECAf0DgAD2gAEACACmAAAACf78/P39/f39/v+GPwEB+/r4+Pj39/j6/fz8/f39/fz7+/n29fX29gICAgIDAfr19fX1+f7/AAIG' +
  'CAgICAUA/wIC//z29vb2/P8DCQkECQkDAP2BgQ4BAgECAQECAgICAQEC+P6EPQH///8AAQEBAgICAgICAgICBAYGBgQEDAwKCgoK' +
  'A/cC/vr4+Pj4+v4BAQUJCgoKAAsLBgIC/vn5+f4CAgYLgwCAAQAIADAAABgXAQECAgECAQEBAQIBAgUDAgICAgMCAgICF/v7/Pv7' +
  '/Pv7+/v7/PgH//UB/wH1AwcD/YEAAYEDAQEB/4IL9wAFAAX8APz8AgkAgAEACABmAAAACv///v7+/f4CAQEBgRcFBQQEBAMGCAcH' +
  'BwYGBwcHCAYDBAQEBQWBCgEBAQL+/f7+/gAFgQv6///+//79AQIBAQKBIQIBAQIB/f7//v//+vr7+/v8+fj5+fj6+vj5+fj5/Pv7' +
  '+/qDAIABAAgABwAAAIAC/QABgYWAAQAIAAcAAACAAv8AAYGFgAEACAAFAAAAggABgYWAAQAIAAUAAACCAAGBhYABAAgABwAAAIAC' +
  '/AABgYWAAQAIAAcAAACAAgMAAYGFgAEACAAtAAAAF/39AQEICAEBCAgBAf7y/f37B/39BAoA/oGCB/X1Bgb7+wsLgwX6+gYG+vqE' +
  'gAEACAAHAAAAgAIBAAGBhYABAAgABwAAAIACAwABgYWAAQAIAAcAAACAAvsA/oGFgAEACAAHAAAAgAL9AP6BhYABAAgABwAAAIAC' +
  '/gD+gYWAAQAIAAcAAACAAvoA/oGFgAEACAAFAAAAggABgYWAAQAIAAcAAACAAv8ABYGFgAEACAAHAAAAgAIBAAWBhYABAAgABwAA' +
  'AIACAgAFgYWAAQAIAAcAAACAAv4ABYGFgAEACAAHAAAAgAIBAAWBhYABAAgABQAAAIIAAoGFgAEACAAHAAAAgAL9AAKBhYABAAgA' +
  'BwAAAIAC/wACgYWAAQAIAAUAAACCAAKBhYABAAgABwAAAIACAQACgYWAAQAIAAcAAACAAvwAAoGFgAEACAAHAAAAgAL/AAKBhYAB' +
  'AAgABwAAAIAC/wD+gYWAAQAIAAcAAACAAv0AAYGFgAEACAAHAAAAgAL/AAGBhYABAAgABQAAAIIAAYGFgAEACAAHAAAAgAL8AAGB' +
  'hYABAAgABQAAAIIAA4GFgAEACAAgAAAQDwEBAwECAQIBAgIBAgICAgIPCAH39/sBCAIDAgICAv0IAQEHB4EI+PgDAwIA//79goAB' +
  'AAgABwAAAIAC/gABgYWAAQAIAAcAAACAAv4AAYGFgAEACAAHAAAAgAL+AAGBhYABAAgABwAAAIAC/gABgYWAAQAIAAcAAACAAvwA' +
  'AYGFgAEACAAHAAAAgAICAAGBhYABAAgAVgAAKikCAwQBAQECAQICAQEDAgEEAgEBBAEBAQMDAgECAgIBAgEBAQEBAQIDAQIp9/f3' +
  '9/f3AQD28O/29vz2AwgIA/39/f/2AQf9/f36+vz7+vv9/gHs+gDzKQEBAgD/AfwDCgYD/AAJA/wCBgkCAgQE/fkABAICBQgB+vr9' +
  '/wAE/vj+AIABAAgABwAAAIAC/wD9gYWAAQAIADYAABoZBQMDAQEBAQEBAgEBAwIBAQMCAQEDAQEBAQEZ/fz49/j5+fwAAgICAPz4' +
  '9vb/BAgIBP76AgYZAQABAgICAQEKBAIFAAoHA/339/0ECv3/CgeAAQAIAAcAAACAAv0A/IGFgAEACAAHAAAAgAL8APyBhYABAAgA' +
  'BwAAAIAC/QD8gYWAAQAIAAcAAACAAvoA/IGFgAEACAAHAAAAgAL+AP+BhYABAAgABwAAAIACAQAFgYWAAQAIAAUAAACCAAWBhYAB' +
  'AAgABwAAAIACAQAFgYWAAQAIAAcAAACAAv8ABYGFgAEACAAHAAAAgAL9AAGBhYABAAgABwAAAIAC/gD/gYWAAQAIAAcAAACAAv0A' +
  '/4GFgAEACAAHAAAAgAL+AP+BhYABAAgABwAAAIAC/gD/gYWAAQAIAAcAAACAAvsA/4GFgAEACAAHAAAAgAL7AP+BhYABAAgABwAA' +
  'AIAC/wD/gYWAAQAIAEwAACUkAQEBAQEBAQMDAQEDAQIBAQIBAQIDAgEFAQIEAQEBAgECAgEBAwoDBAUEDw4I/P8DBIEX///9+/v/' +
  'Agn9/QIEBgkLDAwLCAgHBwcGgAwB//wBBgkH/vz7/P7/gRT8+ff3/QD9AP/9/f3//wIEBAMDAQAAgAEACAAHAAAAgAL/AAGBhYAB' +
  'AAgABwAAAIAC/gABgYWAAQAIAAcAAACAAv8AAYGFgAEACAAHAAAAgAL9AAGBhYABAAgABwAAAIAC/gABgYWAAQAIAAcAAACAAv0A' +
  'AYGFgAEACAAtAAAWFQECAQEBAQMBAwICAQEBAgIBAgMDAgMV/QkKCQgFAgICAwUICQoJ+/f3/wgI/4AGBwcFAwICAoIK//37AAoE' +
  'AfgBBAAAgAEACAAzAAAZGAECAgEDAgIBAQQCAQMCAgIBAQMBAQMBAgEJ/f/+//n/BAX//4IL+/v7/P38+fkCBgYCgAsBAgL++/4A' +
  'AgEABQWBAP+BBgUB/v7/BAWAAQAIABIAAAgHAgUHAgMBAgEH/gH6+gIGBgKABgEC//v/AgaAAQAIAGAAAC8uAgECAgECAQMBAQID' +
  'AQQDAgIBAQEBAQEBAgEBAQECAQEDAgEDAQEBAgECAQEBAQMu/f0FBQD59fn9/v37/fz9/fT09Pj8/QAFBQL9//39//7+/Pb09Pr9' +
  'AwQFBQX++vouAQD+BAgIA/z7+////v8A/wH++/j4+Pj6AgUGBgIBAQECAAYB//79+/r/AAIDBAAAgAEACAAmAAASEQEBAgEBAQIC' +
  'AgICAQIBAQQBAhH++/39/f39/Q0EB/r++gEGAgkG+/v8/v3+/4EI+AAD+Pj4/wMAgAEACACMAAAAPwH//v7+/v7+/wEDBAYGBgYG' +
  'BgQDAQIB/v7+/gECAQMFBQUFAwECAwMDAwIBAgEBAfv7+/0BBAkJCQkDAf/7+/sFAQEBAQAEgYEFAQH/Af//gwX//wH/AQGBLwgI' +
  'CAX+Avv4+Pj4+wL+BQgFBQUD/vz7+/v8/P39/Pn09PT5/gMIDAwMCAMDAwQEBYMAgAEACAAjAAATEgAQAwMDBAQBBAEBAgMCAQID' +
  'AgMS/v79/v/+/v7+/v79/f///v3+/IACAQD/ggABgQD/hQH/AIABAAgAJAAAERABAgICAgICAgICAgICAgICAhD7//v/+wX9BwMH' +
  'Awf9Bf0FAhD7BfsFAAUABfsF+wD7AAX7AACAAQAIAGgAAAADA/39/4IO//39AwMDAQD//f39AwMBghoBAwP9/f3/AAEDAwD++vf3' +
  '9/r+AAMGCQkJBgKDDP0DAwMBAP/9/f0DAwGCDgEDA/39/f8AAQMDA/39/4IR//0JCQcDAP359/f3+f0AAwcJgwCAAQAIAEQAACIh' +
  'AQEBAQIBAgIDAwEBAQMCBQICAQIBAQECAQEBAgEBAgMCAiH+/f39CAgC/Pf7Av/9/f4C9vb5/wIICAYDAvsCAgIC+QT+gB0BAf8B' +
  '/woKAPv6+vr+AP0A+vf29vn+AwQEBgUDAwGCgAEACAAiAAAQDwACAgIBAwECAgEEAgICAgMP/v7+/v4CAwb6+gYJAwkFAoADCvsD' +
  '/4EI//4A9gAD+woAgAEACAAsAAAAE/r6+fsI/wH4BQcGBvr6Bgb6+gYGg4AB/PyBAQkJgQr8/AD1/v71/QUF/YMAgAEACAAmAAAT' +
  'EgADAwMDAQEBAwMDAQMBAQECAwIS//7+/wIC9/gACQkH/Pj3AgH7BIEOAgICAf79+P8DBwoGBAH/gQCAAQAIAA4AAAAFA/76/wD9' +
  'gYACBQD7gwCAAQAIAD0AAB4dAAEBAQIDBAQBAgEBAQQCAQEHAwMCAgIBAQMBAQEEHQP++f/9/f7///v39/cBBQUF/v////v39/cC' +
  'BgYG/YAaBQD7Af/+AAEHAv8A+AD/AgD/AQIIAAH++f4BgQCAAQAIAAgAAACAAwQEAASBhgCAAQAIAAYAAACAAQQBg4YAgAEACAAF' +
  'AAAAgwD/gYaAAQAIAA4AAAYFAQICAgICBfsA+wUABQX7BQAF+wCAAQAIABsAAAAKA/z4/AMA/QQIBP2EC/0EAPwDBwP8AAT9+YOA' +
  'AQAIAB0AAA4NAAIDAgEDAQEEAQEEAgGBC/77+wIFBf77+wIFBQ37BfT6+//7+gEFBgwGBQCAAQAIAAsAAACLB/4ICP74AgL4g4AB' +
  'AAgADwAAAIQBCgqEgAb5BwD3Af8Jg4ABAAgADwAAAIEB9vaHgAYJ/wH3AAf5g4ABAAgAEQAACAcBAgICAgIBAgX7APsFAAWBB/sF' +
  '/QX7AwAKAIABAAgADwAAAAf/+AgB9gH/CoOEAfr6hIABAAgAQAAAAAT89v39/4EMAgECAgICAwUECgMCAYEH/v/+/v7+/PuDHfgB' +
  'BQUFBQUHCAgICAgJCgj/+/r7+/v5+Pj4+Pj39oMAgAEACAAHAAADAgECAgD2gQL7BfOAAQAIABoAAAwLAgMDAgMDAQMBAgIEgAr/' +
  'AgMEAv/9/wQHAwv9/wD//gQE/Pn5/gCAAQAIAAUAAACBAASBhIABAAgABQAAAIEABIGEgAEACAAFAAAAgQAIgYSAAQAIAAgAAAMC' +
  'AQICAv0B/gIG/gAAgAEACAAFAAAAgQABgYSAAQAIAAwAAAAD/fwHBYMD/wIC/4MAgAEACAAFAAAAgQADgYSAAQAIAAUAAACBAP+B' +
  'hIABAAgABQAAAIEA/YGEgAEACAALAAAAA/39CQWDgAECAoSAAQAIABAAAAcGAQMDAQMEAgb+/QUD/gYEBv8CBAUEAv8AgAEACAAN' +
  'AAAGBQACBAIFA4AE/QUC/ASBAwIFAgAAgAEACAAgAAAPDgEBAQEDBAEBAQEBAQEDAg7//f37/v3+/f38AwQDBQAI/v37AQMCAQEB' +
  'gQMCAv/+AIABAAgAFAAAAAf9+wgG/QIBBoMH/wIC///9/f+DAIABAAgAEwAAAAf9+QgF/AEABoOAAQICgQH+/oSAAQAIABoAAAwL' +
  'AgEEAgEBAgEBBAIBCwEBCAwMCAD9/QQHBwv/AgcC//39/wIHAv+AAQAIABoAAAwLAQEBAgQBAwEBBAIBCwYCAgYNDQD9/QQHBwv/' +
  'AQQJBAH/AQQJBAGAAQAIAA4AAAYFAAEDAQEEBQL//f8CBwX9/QQHBwCAAQAIABIAAAgHAAECAQEBAgEHAv/9/f8CBwcH//8DBggI' +
  'BgOAAQAIABQAAAkIAQIBAgICBAECCPz/9gQABPwG/wj9AwAD/QD8AwAAgAEACAAMAAAAA//9CAeDAP2BAP2DAIABAAgADAAAAIAC' +
  '/QgJgwP/AQH/gwCAAQAIAC4AAAAKCQgICQkJExMJCQGBCAEBAQsLAQEACYET/fsGBAT3Af8J/f37BgQE9wH/Cf2DAIABAAgALQAA' +
  'AAkICP7+CAgICQkIgQH29oIBAQGBAAmBE/0J/wH3BAQG+/39Cf8B9wQEBvv9g4ABAAgABwAAAwIBAgIC/QgFAAKBgAEACAAOAAAG' +
  'BQADAwEBBAX+/QgICAWABAkCBgQAgAEACAApAAAUEwECAQECAQECAQICBAIBAQECAQICE/0ICAT/+fkFBQUD/fz8/gEICQgBCQIC' +
  'BwkJBf8CCQmBAf7+gQH++4EAgAEACAAFAAAAgAD/gYOAAQAIABEAAAAJ/v79Bf/1BQUAA4GAAf39iIABAAgABQAAAIEAA4GEgAEA' +
  'CAASAAAIBwEFAgIDAQUDB/3+///8+/8BB/8BAf8DAv0CgAEACAAQAAAHBgEFBAMDAwMG/f7//Pv/AYAFAgAEAP4CAIABAAgADAAA' +
  'AAMD/QAGgwP+AQL/gwCAAQAIAAwAAAADAv0HDIMD/gIFAYMAgAEACAAFAAAAgQD6gYSAAQAIAAgAAAMCAQICAv0GAwIF/gAAgAEA' +
  'CAAlAAASEQACAQEBAQEDAwIBAwIBAgICAxH+/v4GBgL+9/799P7/BAL///2BD/8BBAYGAv0A+gD8AP8BAQAAgAEACAAFAAAAgQD9' +
  'gYSAAQAIAD0AAAADAf39/oECAQEBgRIBAQMDAQYFBAICAgECAgICAQD/gxH/AwMEBAQEBAYHCAgICgoFAgGEBv/9/f39+/qDgAEA' +
  'CABAAAAABAH9/f7/gQz///7+/wABAgAEBAIBgQcBAgICAQD//4Md/QIAAQEBAQMEBgUFBQcHAv7//v7+/vz7+vr6+vn5gwCAAQAI' +
  'ACIAABIRAQECAgUBAQEBAgECAwEBAQICgQT++AMHCIIH/wD/AgcIAP8HAwUFAvr9AAGCBP//AQMGgQAA';

/** Satori'nin beklediği biçim: `ArrayBuffer`. */
export function ogFontData(): ArrayBuffer {
  const bytes = Buffer.from(OG_FONT_BASE64, 'base64');
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
}

export const OG_FONT_NAME = 'Space Grotesk';
