/**
 * OG görseli için gömülü font — T-028 / T-028b.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * 1) NEDEN ÖZEL FONT: VARSAYILAN TÜRKÇE TAŞIMIYOR
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * ÖLÇÜLDÜ (cmap tablosu okunarak): `@vercel/og`in varsayılan fontu
 * `noto-sans-v27-latin-regular.ttf` İ (U+0130), ğ (U+011F), Ğ, ş (U+015F), Ş
 * harflerini İÇERMİYOR; yalnızca ı, ç, ö, ü var. Font verilmezse `satori`
 * eksik harfleri `fonts.googleapis.com`tan indirmeye çalışır: üretimde AĞ
 * BAĞIMLILIĞI, çevrimdışında boş kare. "Yazılım Geliştirme" sessizce bozulurdu.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * 2) NEDEN STATİK ÖRNEK — BULGU-014'ÜN KÖK NEDENİ
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * İlk sürüm depodaki fontu doğrudan alt kümeleyip gömüyordu ve ÇALIŞMA
 * ZAMANINDA çöküyordu:
 *
 *   TypeError: Cannot read properties of undefined (reading '256')
 *     at parseFvarAxis (@vercel/og/index.node.js)
 *
 * ÖLÇÜLDÜ — suçlu alt kümeleme DEĞİL, DEĞİŞKEN FONT:
 *   - alt kümelenmiş Space Grotesk  → çöküyor
 *   - alt kümelenMEMİŞ Space Grotesk → AYNI ŞEKİLDE çöküyor
 *   - alt kümelenmemiş Inter         → aynı hata (reading '257')
 *   - paketin kendi Noto'su          → çalışıyor
 * Fark: ilk üçünde `fvar` (font varyasyon) tablosu var, Noto'da yok.
 *
 * SEBEP paketlenmiş opentype.js'te: `fvar` ayrıştırıcısı eksen adlarını
 * `names[nameID]` ile okuyor, ama o yapıda `case "name":` dalı ve
 * `font.names` ataması HİÇ YOK (ikisinin de sayısı 0 ölçüldü) — yani
 * `font.names` daima `undefined`. Sonuç: `fvar` TAŞIYAN HER FONT çöker.
 * Depodaki üç font da değişken (Space Grotesk wght 600–700).
 *
 * ÇÖZÜM: değişken font `wght=600`e sabitlenip STATİK örneğe çevrildi
 * (`fvar` ve `gvar` tabloları kalkıyor), sonra alt kümelendi: 16 KB.
 * Görünüm depodaki başlık fontuyla aynı — 600 zaten varsayılan eksen değeri.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * 3) NEDEN DOSYA DEĞİL BASE64
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `output: 'standalone'` yalnızca izlenen dosyaları kopyalar; `fs.readFileSync`
 * ile okunan bir varlık `outputFileTracingIncludes` gerektirirdi — o ise
 * `next.config.ts`, yani ORTAK DOSYA. Modül olarak gömmek bu bağımlılığı kaldırır.
 *
 * ───────────────────────────────────────────────────────────────────────────
 * YENİDEN ÜRETMEK İÇİN (gizemli ikili dosya bırakmamak adına):
 *   fonttools ttLib.woff2 decompress src/app/fonts/space-grotesk.woff2
 *   fonttools varLib.instancer space-grotesk.ttf wght=600 -o sg-static.ttf
 *   pyftsubset sg-static.ttf --drop-tables+=GSUB,GPOS --output-file=og-font.ttf \
 *     --unicodes="U+0020-007E,U+00A0-00FF,U+011E-011F,U+0130-0131,\
 *                 U+015E-015F,U+2013-2014,U+2018-201D,U+2026"
 *
 * ⚠️ Bu fontu güncelleyen: `fvar` tablosu OLMADIĞINI doğrula. Değişken bir font
 * gömmek derlemeyi GEÇER, testleri GEÇER ve yalnızca gerçek istekte çöker.
 * `tests/unit/og-font.test.ts` bunu kapı olarak zorluyor.
 */

const OG_FONT_BASE64 =
  'AAEAAAANAIAAAwBQR0RFRgMXAxgAAD20AAAAXk9TLzIR6fPyAAA5lAAAAGBTVEFUeHBojAAAPhQAAAAcY21hcJGbbesAADn0AAAB' +
  'uGdhc3AAAAAQAAA9rAAAAAhnbHlmTJ6FvAAAANwAADK8aGVhZC3ewqAAADWQAAAANmhoZWEIXQH6AAA5cAAAACRobXR4ynQpvwAA' +
  'NcgAAAOobG9jYTSoKCAAADO4AAAB1m1heHAA+wDDAAAzmAAAACBuYW1lKrZDtAAAO6wAAAHecG9zdP+fADIAAD2MAAAAIAACABQA' +
  'AAJlArwABwALAABzEzMTIychBxMzAyMUwNHAfCr++ypGzV4RArz9RKCgAQ4BYwAAAwAuAAACawK8ABkAIwAtAABzNTMRIzUhMhYW' +
  'FRUUBgYHFR4CFRUUBgYjJzMyNjU1NCYjIzUzMjY1NTQmIyMuXl4BZj9fNSQyFxc1JTdfPpOFMDk4MYWELjk5LoRqAehqK083CTA+' +
  'IgcRBiE/Mgo5UyxtLysJKy9tLikKKS4AAQA0//ICVwLKAB8AAEUiJjU1NDYzMhYVFSM1NCYjIgYVFRQWMzI2NTUzFRQGAUyAmJiA' +
  'gIt2SUxKVVVKTEl2iw6RiKaIkYx6BglCVVtQqk9cVUIRDnqMAAIALgAAAmsCvAANABcAAHM1MxEjNSEyFhUVFAYjJzMyNjU1NCYj' +
  'Iy5eXgEdjJSUjEdIVVJSVUhqAehqjo6Ejo5tWFOLVVcAAAEARQAAAggCvAALAABzESEVIRUhFSEVIRVFAb7+uwEp/tcBSgK8bbht' +
  'vW0AAQBFAAAB+QK8AAkAAHMRIRUhFSEVIRFFAbT+xQEi/t4CvG25bv7YAAEANP/yAlYCygAnAABFIiYmNTU0NjMyFhUVIzU0JiYj' +
  'IgYVFRQWMzI2NTUjNSERIzUjDgIBOEp1RZiAgIp2IEIySlVVTExGsQEnbhEIIj8OQX1bpoiRiXQECChAJVtQqk9eUkAMZv6gRRIn' +
  'GgAAAQBFAAACSwK8AAsAAHMRMxEhETMRIxEhEUV5ARR5ef7sArz+2gEm/UQBKP7YAAEARQAAAL4CvAADAABzETMRRXkCvP1EAAEA' +
  'Iv/yAjMCvAAVAABFIiY1NTMVFBYzMjY1ESM1IRUjERQGAQprfXg4NTIzeAE/TnQOdWs/PzQ8PDQBfW1t/oNtcwAAAQBFAAACaAK8' +
  'AAwAAHMRMxEzEzMBASMDIxFFeRH0m/7PATuf+hECvP7jAR3+p/6dASP+3QAAAQBFAAACBgK8AAUAAHMRMxEhFUV5AUgCvP2xbQAA' +
  'AQBFAAADKAK8AA8AAHMRMxMzEzMRIxEjAyMDIxFF4YgRieB0EYjIiBECvP2VAmv9RAJl/ZsCZf2bAAEARQAAAlcCvAALAABzETMT' +
  'MxEzESMDIxFF5qUQd+WlEQK8/ZUCa/1EAmv9lQACADT/8gJuAsoADQAbAABFIiY1NTQ2MzIWFRUUBicyNjU1NCYjIgYVFRQWAVGC' +
  'm5uCg5qag05XV05NV1cOkYimiJGRiKaIkWxbTq5OW1tOrk5bAAACAEUAAAJAArwADQAXAABzESEyFhYVFRQGBiMjEREzMjY1NTQm' +
  'IyNFARtCZDo7ZUCiljQ/PjWWArw0X0EOQGA0/voBczgxCjE4AAMANP9RAm4CygANABsAJgAARSImNTU0NjMyFhUVFAYnMjY1NTQm' +
  'IyIGFRUUFhMiJjU1MxUUMzMVAVGCm5uCg5qag05XV05NV1d6Ljl0HD0OkYimiJGRiKaIkWxbTq5OW1tOrk5b/vM5MEY0Hl0AAgBF' +
  'AAACSwK8ABYAIAAAcxEhMhYWFRUUBgcVFhYVFSM1NCYjIxERMzI2NTU0JiMjRQErQmI3PiwnLXgbHsamNDs6NaYCvC5TOgtBThIQ' +
  'AjIq59YZH/7yAXs3LgkvNwAAAQAl//ICPALKADQAAEUiJiY1NTMVFBYzMjY1NCYmJycuAjU0NjYzMhYWFRUjNTQmJiMiBhUUFhYX' +
  'Fx4CFRQGBgE2UHtGd1RGR0giQS4eRWU2PG5KSnRDdyI+Kj5AHTkrHkhsPUF1DjlsThoaRUQ6Lh8nGAsGEDFOPz9aMDJkSyEhKzQY' +
  'MCwcJxkJBxAxUEA/YDYAAAEAGQAAAjMCvAAHAABzESM1IRUjEerRAhrRAk9tbf2xAAABAEH/8gJdArwAEwAARSImJjURMxEUFjMy' +
  'NjURMxEUBgYBT1R5QXhOSElNeEB6Dj10UAHJ/jRGTExGAcz+N1B0PQABABQAAAJXArwABwAAcwMzEzMTMwPOunyeDp98uwK8/ZEC' +
  'b/1EAAEAIAAAA10CvAAPAABzAzMTMxMzEzMTMwMjAyMDgWF3TBFi0WIRS3hi0WMRZAK8/ZcCaf2XAmn9RAJ1/YsAAQAYAAACagK8' +
  'AA0AAHMTAzMTMxMzAxMjAyMDGNPQiZURlIrQ0omXEZcBYQFb/voBBv6l/p8BDP70AAEACQAAAmMCvAAJAABzNQMzEzMTMwMV+vGH' +
  'nhGehvH3AcX+ywE1/jv3AAEALwAAAhQCvAALAABzNQE1ITUhFQEVIRUvAWX+pQHX/psBaZoBqA5smv5YDmwAAAIAKf/yAisB/AAm' +
  'ADEAAFciJiY1NDY2MzM1NCYjIgYHJz4CMzIWFRUUMzMVIyImNTUjDgInMjY1NSMiBhUUFuI0VDExVjePMDMyMwhqDDVYQGFvHCpR' +
  'JC4RBh49ITlIiCUuMA4lRjMyRCMeJzEvJSMnQCdhXMIeXyQfAg4oHV5BNwogHx4lAAACAEn/8gJOArwAFgAkAABFIiYnIxUjETMR' +
  'Mz4CMzIWFhUVFAYGJzI2NTU0JiMiBhUVFBYBbUZLERFxcxELJz8vPWY+PmdePlJRPz5TUw4xHkECvP70FCIWO3JQEFByO2RRSwpM' +
  'UFBMCktRAAABADH/8gImAfwAIgAARSImJjU1NDY2MzIWFhcHLgIjIgYGFRUUFhYzMjY3Fw4CATBIdENDdEhHZT4JbwQeNygpQSUl' +
  'QSk9PwhvDD5lDjxyUA5QcjwyVzYXHzMeI0YxCjFFJD8yGjRWMwAAAgAx//ICNgK8ABYAJAAARSImJjU1NDY2MzIWFhczETMRIzUj' +
  'BgYnMjY1NTQmIyIGFRUUFgETPGg+Pmc9LkAnCxFycBESSiQ+UlE/PlNTDjtyUBBQcjsWIhQBDP1EQR4xZFFLCkxQUEwKS1EAAgAx' +
  '//ICGAH8ABkAIAAARSImJjU1NDY2MzIWFhUVIRYWMzI2NxcOAgMzJiYjIgYBK0pxPz5wSUhsPP6NAk45ODYOXw41WMj9BEM1N0IO' +
  'P3NNDE5yPz9yTCk6RjEfMRs9KwE7MTo6AAABABsAAAGZArwAEgAAcxEjNTM1NDYzMxUjIhUVMxUjEZ+EhDkvgFociIgBj19kMTlf' +
  'HlFf/nEAAAIAMf84AjYB/AAdACsAAHc1NDY2MzIWFzM1MxEUBiMhNSEyNTUjDgIjIiYmBTI2NTU0JiMiBhUVFBYxPmg+RkkREXA4' +
  'MP60ASUdEQsmPi8+aD4BBD5SUT8+U1P1D05vOzIdQf20MTlkHo8RIxg7b0VPRwpITk5ICkdPAAABAEkAAAIjArwAFgAAcxEzETM+' +
  'AjMyFhYVESMRNCYjIgYVFUlzEQgkOy05WDFzOzY9RgK8/vERIhYzXD/+2AEfPDtRS/r//wA2AAAAzgLDBiYA2QAAAAYA0gsA////' +
  '7P84ANACwwYmANoAAAAGANINAAABAEkAAAIeArwADAAAcxEzETM3MwcXIycjFUlzEbKX7/eVvBECvP53u+//yckAAQBJAAAAvAK8' +
  'AAMAAHMRMxFJcwK8/UQAAQBJAAADEwH3ACUAAHMRMxUzNjYzMhYXMzY2MzIWFhURIxE0JiMiBhURIxE0JiMiBhURSXERDT0zNkIR' +
  'EBFAOy5LLXMuKS01ci4pLjQB7jcZJywiIiwoTjr+uQE/Ky07N/7bAT8rLTs3/tsAAQBJAAACIwH3ABUAAHMRMxUzNjYzMhYWFREj' +
  'ETQmIyIGFRVJcRENREU5WDFzOzY9RgHuRRwyNFw//tgBHzw7UUv6AAACADH/8gI0AfwAEQAfAABFIiYmNTU0NjYzMhYWFRUUBgYn' +
  'MjY1NTQmIyIGFRUUFgEzSnVDQ3VKSnRDQ3RKP1BQPz9QUA49cU8QT3I8PHJPEE9xPWZRSQpJUVFJCklRAAACAEn/OAJOAfwAFgAk' +
  'AABXETMVMzY2MzIWFhUVFAYGIyImJicjERMyNjU1NCYjIgYVFRQWSXEREUtGPGc+PmY9Lz8nCxGPP1FSPj5TU8gCtkEfMDtyUBBQ' +
  'cjsWJBL++gEeUUsKTFBQTApLUQACADH/OAI2AfwAFgAkAABFESMOAiMiJiY1NTQ2NjMyFhczNTMRATI2NTU0JiMiBhUVFBYBxBEL' +
  'J0AuPWc+Pmg8RkoSEXD+/z9RUj4+U1PIAQYSJBY7clAQUHI7MB9B/UoBHlFLCkxQUEwKS1EAAAEASQAAAWoB8AAOAABzETMVMzY2' +
  'MzMVIyIGFRFJcRELNCQ8PjI+Ae45HxxmNTf+4gAAAQAs//IB4gH8ACoAAEUiJic3HgIzMjY1NCYnJy4CNTQ2MzIWFwcmJiMiBhUU' +
  'FhcXHgIVFAYBFWB8DWoHJDUfLy8tLh8zVDNrV1NsEGoINicoKywlHzdZNG8OVFEbJiwSIhobGgkFCiM9L0hOSj4gKiMcGhoaBgYK' +
  'IDwzTVMAAQAbAAABnQKNABIAAGEiJjURIzUzNTMVMxUjERQzMxUBBTA5gYFzjo4cYzkxASVfn59f/u4eXwABAEX/+AIeAe4AFQAA' +
  'RSImJjURMxEUFjMyNjU1MxEjNSMGBgEGOVgwcjs2PUdycBENRQgzXT4BKP7hPDpQS/r+EkUbMgAAAQAUAAACDgHuAAcAAHMDMxMz' +
  'EzMDtqJ6ehF7eqIB7v5mAZr+EgABACsAAALpAe4ADwAAcwMzEzMTMxMzEzMDIwMjA3hNcjURS7hLETVyTb9KEUsB7v5fAaH+XwGh' +
  '/hIBof5fAAEAHgAAAjIB7gANAABzNyczFzM3MwcXIycjBx64tYZ5EXmFtbiHehF6+fWrq/X5rq4AAQBF/zgCHgHuAB0AAFc1ITI1' +
  'NSMOAiMiJiY1ETMRFBYzMjY1NTMRFAYjgAERHBEIJDwuOVgwcjs2PUdyODDIZB6KEiMXM10+ASj+4Tw6UEv6/bQxOQABADYAAAHU' +
  'Ae4ACwAAczUlNSE1IRUFFSEVNgEa/vABjP7mASKK9g9fivYPXwAAAgA0//ICUgLKAA0AGwAARSImNTU0NjMyFhUVFAYnMjY1NTQm' +
  'IyIGFRUUFgFDe5SUe3yTk3xPS1JISlBNDoqLroiNjYiui4poWFG3UlZYULdTVgAAAQANAAABdgK8AAcAAGERIwcjEzMRAQIRaXuV' +
  '1AJo5QE5/UQAAQAtAAACKwLKACkAAHM1NDY2Nzc+AjU1NCYjIgYVFSM1NDY2MzIWFhUVFAYGBwcOAhUVIRUtMVxCQCc2Hko+Pk50' +
  'RHRISHNBNl88Pi01FgGBUUpfPRQUDSQ1JAQ2P0NBEQ9Majg3YkIKQ1w7ExMOICkfB2gAAAEAJf/yAjQCvAAlAABFIiYmNTUzFRQW' +
  'MzI2NTU0JiYjIzU3NSE1IRUHFTMyFhYVFRQGBgEwTnlEdFNEREwjOyWG7f6SAe7gKTJbOkF1DjhpSRIPPUhDMwkkLBWChQ9onH4P' +
  'J1BAC0RkNwACABsAAAJiArwACgAPAABhNSE1EzMRMxUjFSUzESMDAXn+ov/TdXX+nu4R3Y6HAaf+OmiO9gF8/pMAAQAp//ICMgK8' +
  'ACgAAEUiJiY1NTMVFBYzMjY1NTQmIyIGBgcjESEVIRUzPgIzMhYWFRUUBgYBL1F1QHZJRUVMSzkgKRoIkAHZ/psRCyM5KD5lPD50' +
  'DjpqRgoJOUpMPgk9SBIbDgGFarwPGxM1ZkoLSWw8AAACADT/8gI+AsoAIQAxAABFIiYmNTU0NjYzMhYWFSM0JiMiBhUVMzY2MzIW' +
  'FhUVFAYGJzI2NTU0JiYjIgYGFRUUFgE3TnRBRHdOTnE9dj9HR00REUpEPmdAQnZNQk4jQSwrQiNODjtqRvFTcDk1YUIuQktCThcn' +
  'NGRGDEZpOmhHOwgpOiEhOikIO0cAAAEAHAAAAhMCvAAPAABzNTQ2NxM1ITUhFQEGBhUViAwU8v6CAff/AA0JGiY1IwGtD2iK/jcX' +
  'IxoVAAADACH/8gI9AsoAJQAzAEEAAEUiJiY1NTQ2Njc1LgI1NTQ2NjMyFhYVFRQGBgcVHgIVFRQGBicyNjU1NCYjIgYVFRQWEzI2' +
  'NTU0JiMiBhUVFBYBL1F6QyQ2GBgxH0F1Tk11QR8vGRk1JER6UElRUEpKUFFJREtNQkJNSw4wWz0MMUAkBxEIJDwrDDdTLi5TNwwr' +
  'PCQIEQckQDEMPVswaDgxCDA5OTAIMTgBQTIuCC0yMi0ILjIAAAIAK//yAjQCygAhADEAAEUiJiY1MxQWMzI2NTUjBgYjIiYmNTU0' +
  'NjYzMhYWFRUUBgYDMjY2NTU0JiMiBhUVFBYWASxOcT52QUZHTRESSEY9aD9Cdk5OdUBDd0stQCROQ0JOJEEONWFCLkJLQk4XJzRk' +
  'RgxHaDo7akbxU3A5AWIhOygIPEZGPAgoOyEAAQBJ/w0BUALxABEAAFciJjURNDYzMxUjIhURFDMzFakqNjYqp30bG33zNioDJCo2' +
  'Yh79HB5iAAABABH/DQEXAvEAEQAAVzUzMjURNCMjNTMyFhURFAYjEXwbG3ymKzU1K/NiHgLkHmI2KvzcKjYAAAEAJf8NAbkC8QAj' +
  'AABFIiY1ETQjIzUzMjURNDYzMxUjIhURFAYjIxUzMhYVERQzMxUBEio2IWxsITYqp30bKiMODiMqG33zNioBOSJuIgE5KjZiHv7m' +
  'Ii4QLiL+5h5iAAEAEf8NAaUC8QAjAABXNTMyNRE0NjMzNSMiJjURNCMjNTMyFhURFDMzFSMiFREUBiMRfBsqJA0NJCobfKYqNiJs' +
  'bCI2KvNiHgEaIi4QLiIBGh5iNir+xyJuIv7HKjYAAAEANP8NAYEC8QARAABFIiYmNRE0NjYzFSIGFREUFjMBgWyUTU2UbHBubnDz' +
  'S515ASJ6nEtifob+6IV/AAEAAv8NAU4C8QARAABXNTI2NRE0JiM1MhYWFREUBgYCcG1tcGyUTEyU82J/hQEYhn5iS5x6/t55nUsA' +
  'AAH/9P84AYwCvAADAABHATMBDAEmcv7ayAOE/HwAAAEARf8KALgDJgADAABXETMRRXP2BBz75AAAAgBF/woAuAMmAAMABwAAUxEz' +
  'EQMRMxFFc3NzAW4BuP5I/ZwBuP5IAAH/8/84AYwCvAADAABFATMBARn+2nMBJsgDhPx8//8ANwGbAOQCygYHAFIAAAIp//8ANwGb' +
  'AbQCygQnAFIAAAIpAAcAUgDQAin//wA4AZsA5QLKBA8AUgEcAjzAAP//ADcBmwDkAsoGBwBSAAACKf//ADgBmwG1AsoELwBSAewC' +
  'PMAAAA8AUgEcAjzAAP//ADcBmwG0AsoEJwBSAAACKQAHAFIA0AIp//8AN/9yAOQAoQYGAFIAAAABADf/8gDoAKMACwAAVyImNTQ2' +
  'MzIWFRQGkCYzMyYmMjIOMicmMjInJzEAAAEAN/9yAOQAoQASAABXNTMyNTUjIiY1NDYzMhYVFRQjTiUrECUyMiUmMGmOQCsgLSMl' +
  'LzAnbmr//wA3//IA6AH9BiYAUQAAAAcAUQAAAVr//wA3/3IA6AH9BicAUQAAAVoABgBSAgD//wA3//ICygCjBCYAUQAAACcAUQDx' +
  'AAAABwBRAeIAAAACADf/8gDoArwAAwAPAAB3ETMRByImNTQ2MzIWFRQGVXU6JjMzJiYyMtwB4P4g6jInJjIyJycxAAIAN/84AOgB' +
  '/AADAA8AAFcRMxEDMhYVFAYjIiY1NDZVdTomMjImJjMzyAHb/iUCxDEnJzExJycxAAACACT/8gIXAsoAJAAwAAB3NTQ2Nzc2NjU0' +
  'JiYjIgYGFRUjNTQ2NjMyFhYVFAYGBwcGBhUVByImNTQ2MzIWFRQG2CcuEy8yIDklJz0ldkN0SEduPytEJBQSDjklMzMlJjMz3CAy' +
  'PxUJFjMrIC0YGjMnGhhFYzQ0Wzw7TDARCQgYFhzqMScnMjInJzEAAAIAK/8qAh4B/AAkADAAAEUiJiY1NDY2Nzc2NjU1MxUUBgcH' +
  'BgYVFBYWMzI2NjU1MxUUBgYDMhYVFAYjIiY1NDYBIEdvPyxDJBQSD3gnLhQuMyA6JSY+JHZDcz0mMzMmJTMz1jNcOztNMBEJCBcX' +
  'FxwyPhYJFTItIC0XGTQnGRhEYjUC0jEnJzExJycxAAABAEcAzAFvATMAAwAAdzUhFUcBKMxnZwABAEcAzAIHATMAAwAAdzUhFUcB' +
  'wMxnZwABAEcAzAM3ATMAAwAAdzUhFUcC8MxnZ///ABEAxgDCAXcEBwBR/9oA1AABAET/aAIo/9AAAwAAVzUhFUQB5JhoaAACAEX/' +
  'OAO4AsgARQBTAABFIiYmNTU0NjYzMzIWFhUVFAYjIyImNTUjDgIjIiYmNTU0NjYzMhYWFzM1MxEUFjMzMjY1NTQmJiMjIgYGFRUU' +
  'FhYzMxUDMjY1NTQmIyIGFRUUFgIOjc1vbMeJFX68aFdWNC4wEQggMig+WzIwWDsnMx8KEW4OEAYkH0WJZg9nllFUnm3N5DRAQDQ1' +
  'Pj7IbMeKF4rHa2i8fkBvdyYfBBUlFkJwRRBGcEIUIBI+/pYRDz5DPWONTE6ZcBBxmk5oASNRRgxGUVFGDEZRAAIAIAAAAkICvAAi' +
  'ACsAAHMiJiY1NDY2NzUmJjU0NjYzMxUjIgYVFBYWMzM1MxUzFSMRJzM1IyIGFRQW7z1dNSA2IDFANl07cV0wQB8zHmtyXl7hb28w' +
  'QEMtVDsrQSoKDQ9KPzxUK18zMyMtFl9fX/7OX9M1NDY0AAEALQD+AeoCvAAvAABTNTMXNycnNxcXNyc1MxUHFzc3FwcHFzczFSMn' +
  'BxcXBycnBxcVIzU3JwcHJzc3JwctT0gFOzgwOSkNDEUMDSk5MTk7BUhPT0gFOzkxOSkNDEUMDSk5MDg7BUgBu0UMDCo5MDg7BUdQ' +
  'UEcFOzgwOSoMDEUMDSk5MTg7BUdQUEcFOzgxOSkNDP//ABQAAAJlA3cGJgACAAAABwDWAI4AAP//ABQAAAJlA3YGJgACAAAABwDK' +
  'AMgAAP//ABQAAAJlA3YGJgACAAAABgDPVQD//wAUAAACZQN5BiYAAgAAAAYA6GAA//8AFAAAAmUDiQYmAAIAAAAGANFZAP//ABQA' +
  'AAJlA7IGJgACAAAABwDgAKoAAAACABQAAAMUArwACwAVAABhESEVIRUhFSEVIRUhEzMVIwMzFSMHAXoBlP7jAQH+/wEj/QD2cBB/' +
  'j7M4ArxtuG29bQK8QP6SbqAA//8ANP8sAlcCygYmAAQAAAAHAM0AsAAA//8ALgAAAmsCvAYmAAUAAAAGAOTvAP//AEUAAAIIA3cG' +
  'JgAGAAAABgDWewD//wBFAAACCAN2BiYABgAAAAcAygC1AAD//wBFAAACCAN2BiYABgAAAAYAz0IA//8ARQAAAggDiQYmAAYAAAAG' +
  'ANFGAP//ADT/8gJWA3YGJgAIAAAABwDMAIMAAP////4AAADKA3cGJgAKAAAABgDW0wD//wA4AAABBAN2BiYACgAAAAYAyg0A////' +
  'xQAAAT0DdgYmAAoAAAAGAM+aAP///8kAAAE5A4kGJgAKAAAABgDRngD//wA1AAAAzQOKBiYACgAAAAYA0woA//8ARQAAAlcDeQYm' +
  'AA8AAAAGAOhxAP//ADT/8gJuA3cGJgAQAAAABwDWAKMAAP//ADT/8gJuA3YGJgAQAAAABwDKAN0AAP//ADT/8gJuA3YGJgAQAAAA' +
  'BgDPagD//wA0//ICbgN5BiYAEAAAAAYA6HQA//8ANP/yAm4DiQYmABAAAAAGANFuAP//ADT/pQJuAwsGJgAQAAAABgDhVQD//wAl' +
  '/ywCPALKBiYAFAAAAAcAzQChAAD//wBB//ICXQN3BiYAFgAAAAcA1gChAAD//wBB//ICXQN2BiYAFgAAAAcAygDbAAD//wBB//IC' +
  'XQN2BiYAFgAAAAYAz2gA//8AQf/yAl0DiQYmABYAAAAGANFsAP//AAkAAAJjA3YGJgAaAAAABwDKAMIAAAACAEUAAAJAArwAFQAZ' +
  'AAB3NTMyNjU1NCYjIzUzMhYWFRUUBgYjBREzEb6WND8+NZaiQmQ6O2VA/uV5jW44MAoxOG00X0ENQWA0jQK8/UQA//8AKf/yAisC' +
  'vAYmABwAAAAGANVnAP//ACn/8gIrAroGJgAcAAAABwDGAKcAAP//ACn/8gIrAroGJgAcAAAABgDOMwD//wAp//ICKwKwBiYAHAAA' +
  'AAYA5z4A//8AKf/yAisCvwYmABwAAAAGANA9AP//ACn/8gIrAuIGJgAcAAAABwDfAIcAAAAEACn/8gNJAfwAGAAjAEEASAAARSIm' +
  'JjU0NjYzMhYWFRUhFhYzMjY3Fw4CJTI2NTUjIgYVFBYXIiY1NDYzMzU0JiMiBgcnPgIzMhYXMwcXIw4CEzMmJiMiBgJxSGs7O2dD' +
  'SGQ1/qEDRjg2OA5WEzVM/lE5R4cpMDIiVm9tVY82MzI3C2YONlg+Pk0YGhYKGwoqSsLtAT80NkAOR3lJSXREQG5FODZFLxk8HDQg' +
  'XUM3CCAeHyVdUUtNTCAmMjAkIydAJykhr7ISLCEBNTU8PQD//wAx/ywCJgH8BiYAHgAAAAcAzQCVAAAAAwAx//ECNgMGABgAJwAr' +
  'AABFBiYmNTU0NjY3NhYXMyYmJzceAhUUBgYnMjY2NTU0JiMiBhUVFBYTJzcXATRNdUE+Zz40RhgRFH9kJG+WTUF0TipAJVA/P1BQ' +
  'KDaRNw4BQHRMCktvPgEBIxxPdSJcJIi9c2KEQ2UlRjEFSlJSSgVJUwG9Kcgp//8AMf/yAhgCvAYmACAAAAAGANV1AP//ADH/8gIY' +
  'AroGJgAgAAAABwDGALYAAP//ADH/8gIYAroGJgAgAAAABgDOQQD//wAx//ICGAK/BiYAIAAAAAYA0EwA//8AMf84AjYCugYmACIA' +
  'AAAGAMt8AP////sAAADJArwGJgDZAAAABgDV0AD//wA8AAABCgK6BiYA2QAAAAYAxhEA////xwAAAT4CugYmANkAAAAGAM6cAP//' +
  '/9EAAAEyAr8GJgDZAAAABgDQpgD//wBJAAACIwKwBiYAKQAAAAYA51UA//8AMf/yAjQCvAYmACoAAAAHANUAgAAA//8AMf/yAjQC' +
  'ugYmACoAAAAHAMYAwQAA//8AMf/yAjQCugYmACoAAAAGAM5MAP//ADH/8gI0ArAGJgAqAAAABgDnVwD//wAx//ICNAK/BiYAKgAA' +
  'AAYA0FcA//8AMf+7AjQCLgYmACoAAAAGAOIrAP//ACz/LAHiAfwGJgAuAAAABgDNbwAAAQBJ//ICbALKADwAAEUiJiYnNxYWMzI2' +
  'NTQmJicnJiY1NDY3NjY1NCYjIgYGFREjETQ2NjMyFhYVFAYGBwYGFRQXFx4CFRQGBgGmPlcyCGcJMywoLRUmGSkqKCIgGik3KyJF' +
  'LXJDdk09YDYfMhwKChscKkMnMFgOKkMkICctKyIWHhUJDxAxHyMsFhEvISAmIk9D/ksBsVl+QipLLys9KxIFDAcQCgsPKj8xMUws' +
  'AP//AEX/+AIeArwGJgAwAAAABgDVfwD//wBF//gCHgK6BiYAMAAAAAcAxgDAAAD//wBF//gCHgK6BiYAMAAAAAYAzksA//8ARf/4' +
  'Ah4CvwYmADAAAAAGANBVAP//AEX/OAIeAroGJgA0AAAABwDGAMAAAP//AEX/OAIeAr8GJgA0AAAABgDQVQAAAgBJ/zgCTgK8ABcA' +
  'JQAAVxEzETM+AjMyFhYVFRQGBiMiJiYnIxETMjY1NTQmIyIGFRUUFklyEQwmQC49Zz4+Zz0uQCYMEZA/UVE/PlNTyAOE/vQUIhY7' +
  'clAQUHI7FiMT/voBHlFLCkxQUEwKS1EAAAIAIwFUAY8CxQAiAC0AAFMiJjU0NjMzNTQmIyIGByc2NjMyFhUVFDMzFSMiJicjDgIn' +
  'MjY1NSMiBhUUFqQ3Sks5Xx4jISMGSwtLQkJREyE9Gh8CDAQXKhMnLFcYHyABVDg3NTgRHSMhFhkoOkNEiBVDGBYKGhRFJigLGBMV' +
  'GQAAAgAiAVQBkwLFAAsAFwAAUyImNTQ2MzIWFRQGJzI2NTQmIyIGFRQW2lNlZVNTZmZTLTU1LSw2NgFUYVhYYGBYWGFGOzg3Ozs3' +
  'ODsAAAIAIf/yAbUCygA3AEgAAFciJjU1MxUUFjMyNjU0JicmJjU0NjcmNTU0NjYzMhYVFSM1NCYmIyIGFRQWFxYWFRQHFhYVFRQG' +
  'AzY2NTQmJyYmJwYVFBYXFhb0YnFkNjguLiw5VV4MCxcwUTNWbGMUKR8lLD0wWFMUCgljBwIBKzgTJBEEOzAVHQ5sWhANMTolIiEj' +
  'Cw9MRhgpESItBjFGJVhNGA8XJRQgHiQgCRBNQTIkECYVCEpeAT0DBwYcIwoDCwYIDSAeCQQHAAACABMAAAIXArwAEQAbAABhESMi' +
  'JiY1NTQ2NjMhESMRIxEDMzUjIgYVFRQWAQAXP2E2OGM/ASpjUX8cHDI8PgEhNFk7CzxaMv1EAl79ogF/3zsxBjE8AAMANP/0ApgC' +
  'yAATACMAQwAARSImJjU1NDY2MzMyFhYVFRQGBiMnMzI2NTU0JiMjIgYVFRQWNyImNTU0NjMyFhUVIzU0JiMiBhUVFBYzMjY1NTMV' +
  'FAYBXVqGSUmGWhJbhUlJhVsQD2Fra2EPYmpqbEFNTUFGRFgXGxkbHBgZGVhDDEeHYXZhh0dHh2F2YYdHWGxqeGpsbGp4amxJTkpj' +
  'Sk9OPw8VFx0dGYMZHBwZFA8/TgAEADIBKgHWAsoADwAbAC8AOAAAQSImJjU0NjYzMhYWFRQGBicyNjU0JiMiBhUUFjc1MzIWFRQG' +
  'BxUWFhUVIzU0IyMVNTMyNjU0JiMjAQQ8Xzc3Xzw8Xzc3XzxLXFxLS1xcA1UlJhMVEQ8pFTEsERERESwBKjVePT1eNTVePT1eNSlb' +
  'TEtcW0xLXDreJBgUHAgKARQQOzwVUXcUDQ4TAAIAKQAAAlECvAAbAB8AAHM1IzUzNSM1MzUzFTM1MxUzFSMVMxUjFSM1IxURMzUj' +
  'mXBwcHBoeGhwcHBwaHh4eL9iemK/v7+/Ynpiv7+/ASF6AAACACkAUQJDAmsAIwAzAAB3JzcmJjU0NjcnNxc2NjMyFhc3FwcWFhUU' +
  'BgcXBycGBiMiJic3MjY2NTQmJiMiBgYVFBYWcEc9FRUVFT1HPR1FJyZGHT1HPRQWFhQ9Rz0dRiYnRR2JKkQpKUQqKkQpKURRRz0d' +
  'RScmRh09Rz0UFhYUPUc9HUYmJ0UdPUc9FRUVFTkoRCsrRCgoRCsqRSgAAAIAJf+MAjwDMAA0ADgAAEUiJiY1NTMVFBYzMjY1NCYm' +
  'JycuAjU0NjYzMhYWFRUjNTQmJiMiBhUUFhYXFx4CFRQGBgcRMxEBNlB7RndURkdIIUAuHkVlNz1uSkp0QnYiPio/Px05Kx5Iaj1B' +
  'dYdtDjlsThoaRUQ6Lh8nGAsGEDFOPz9aMDJkSyEhKzQYMCwcJxkJBxAxUEA/YDZmA6T8XAABADYAAAJFAsoAHQAAczUzNSM1MzU0' +
  'NjMyFhUVIzU0JiMiBhUVMxUjFSEVNkpGRnlnaHhyOzMyO2pqAVJou15uaHNzaD1ANTs7NXFeu2gAAAMAAwAAAmkCvAALAA8AEwAA' +
  'cxEnAzMTMxMzAwcRJTUhFSU1IRX6FOOJohCiieMU/ucBuv5GAboBDwoBo/7NATP+XQr+8XVdXZReXgACADT/jAIqAmQAIgAmAABF' +
  'IiYmNTU0NjYzMhYWFwcuAiMiBgYVFRQWFjMyNjcXDgIHETMRATRIdEREdEhGZT4KbwUeNikpQSUlQSk9PwlvDT5leGcOPHJQDlBy' +
  'PDJXNhcfMx4jRjEKMUUkPzIaNFYzZgLY/SgAAQAS//YCbwLGAAMAAFcnARdQPgIfPgoyAp4yAAUAHP/zAt0CyQADABEAHwAtADsA' +
  'AFcnARcDIiY1NTQ2MzIWFRUUBicyNjU1NCYjIgYVFRQWASImNTU0NjMyFhUVFAYnMjY1NTQmIyIGFRUUFpFHAh9Gc0tWVktKV1ZL' +
  'ICUlICAlJf6hS1ZWS0pYVkwhJSUhICUlDTgCnjj9ZFJHB0dSUkcHR1JMKSAPISgoIQ8gKQFNUkYHSFJSSAdGUkwoIQ8gKSkgDyEo' +
  'AP//ABH/9gMqAsYEJgDeAAAAJgCxOgAABwDUAbQAAP//ABH/9gMbAsYEJgDeAAAAJgCxOgAABwDpAcsAAP//ABb/9gNrAsYEJgDm' +
  'AAAAJgCxewAABwDUAfUAAAABAGUAjQIHAi8ACwAAZTUjNTM1MxUzFSMVAQCbm2ybm42daJ2daJ0AAQBkAI0CCAIvAAsAAHcnNyc3' +
  'FzcXBxcHJ65KiIhKiIhKiIhKiI1Kh4dKh4dKh4dKhwADAGUAVQIHAmcAAwAPABsAAFM1IRUHIiY1NDYzMhYVFAYDIiY1NDYzMhYV' +
  'FAZlAaLRIi8vIiIvLyIiLy8iIi8vASpoaNUvISIvLyIhLwFxLyIhLy8hIi8AAgBlANYCBwHmAAMABwAAUzUhFQU1IRVlAaL+XgGi' +
  'AX5oaKhoaAABAGQAggIIAjoABwAAZSU1JRUFFQUCCP5cAaT+zAE0gpWOlW9lEGUAAQBkAIICCAI6AAcAAHc1JTUlNQUVZAE0/swB' +
  'pIJvZRBlb5WOAAACAGUAAAIHAh8ACwAPAABlNSM1MzUzFTMVIxUFNSEVAQCbm2ybm/75AaKfjGiMjGiMn2hoAAABAEcBqAIlArwA' +
  'BwAAUxMzEyMnIwdHmayZgWYQZgGoART+7MrKAAEANQD1AjYBxwAdAAB3Jzc2NjMyFhcWFjMyNjc3FwcGBiMiJicmJiMiBgd1QHEU' +
  'KxwdJQ4NEA0MFAtQQHETLBwdJQ4NDw4MEwz1VFYQFRkTExAMCT1UVg8WGRMUDwwJAAEAZACvAggBkgAFAABlNSE1IRUBov7CAaSv' +
  'e2jjAAIAIQGNAWYCygAPABsAAFMiJiY1NDY2MzIWFhUUBgYnMjY1NCYjIgYVFBbDLUorK0otLkorK0ouHycnHx4oKAGNKUguLkgo' +
  'KEguLkgpWScfHyYlIB8nAP//ACsCKwD5ArwEBgDVAAD//wArAikA+QK6BAYAxgAA//8AKwIpAYwCvwQGANAAAAABACsCOAFvApQA' +
  'AwAAUzUhFSsBRAI4XFwA//8AK/8sARsAFAQGAM0AAAABACsCKQD5AroAAwAAUzczBytLg2gCKZGR//8AEQFeANkCvAYHAN0AAAFe' +
  '//8AGgFeAVACyAYHAOkAAAFe//8AFgFSAVICvAYHAOUAAAFeAAEAKwL2APcDdgADAABTNzMHK0aGZAL2gIAAAQArAiUBbgK6ABEA' +
  'AFMiJjU1MxUUFjMyNjU1MxUUBs1MVmAfIyIfYFUCJUxDBgQeJyceBAZDTAABACsC8AFsA3YAEQAAUyImNTUzFRQWMzI2NTUzFRQG' +
  'zExVXiAjIx9eVQLwRzsEBBkkJBkEBDtHAAEAK/8sARsAFAAXAABXIiYnNxYWMzI2NTQmIyM3MwcyFhUUBgacIDsWFhIqGhQbGBkm' +
  'CE8FJzMkOtQNCUUHCw4QDg5lPSkoHygTAAABACsCKQGiAroABwAAUzczFyMnIwcrd4l3dj0RPQIpkZFMTAABACsC9gGjA3YABwAA' +
  'UzczFyMnIwcrdo11fTYRNwL2gIBERAACACsCKQGMAr8ACwAXAABBIiY1NDYzMhYVFAYjIiY1NDYzMhYVFAYBQSAsLCAhKirrICws' +
  'ICErKwIpKSIjKCgjIikpIiMoKCMiKQAAAgArAvMBmwOJAAsAFwAAQSImNTQ2MzIWFRQGIyImNTQ2MzIWFRQGAU8gKysgISsr+SAs' +
  'LCAhKysC8ykiIygoIyIpKSIjKCgjIikAAAEAKwItAMMCwwALAABTIiY1NDYzMhYVFAZ3Hy0tHyErKwItKSIiKSkiIikAAQArAvMA' +
  'wwOKAAsAAFMiJjU0NjMyFhUUBncfLS0fISsrAvMqIiEqKiEiKgACABMAAAF2AV4ACgAPAABzNSM1NzMVMxUjFSczNSMH4M2OlUBA' +
  'xnAOYkpSws5GSpCShgAAAQArAisA+QK8AAMAAFMnMxeTaINLAiuRkQABACsC9wD3A3cAAwAAUyczF5Blh0UC94CAAAIANAAJAoMB' +
  '5gAJABMAAGUlNSUzFQcVFxUhJTUlMxUHFRcVAn3+2wElBr+//tb+2wElBr+/CbB9sHtrEGt8sH2we2sQa3wAAAIARAAJApMB5gAJ' +
  'ABMAAGU1NzUnNTMFFQUhNTc1JzUzBRUFAWi/vwYBJf7b/ta/vwYBJf7bCXxrEGt7sH2wfGsQa3uwfbAAAAEASQAAALwB7gADAABz' +
  'ETMRSXMB7v4SAAH/7P84AL4B7gAKAABHNTMyNREzERQGIxRDHHM5MMhjHgI1/bQxOQABAEX/OAJfAe4AHgAAVxEzERQWMzI2NREz' +
  'ERQzMxUjIiYnNSMGBiMiJicjFUVzOzU9QnIcKlEkLQIRDUU4IysNEcgCtv7gOTxMSAEB/o8eXyQiBiMxEwzfAAABABEAAADZAV4A' +
  'BwAAcxEjByM3MxGEDRdPMJgBE1Gc/qL//wARAV4A2QK8BgcA3QAAAV4AAgArAhwA+QLiAAsAFwAAUyImNTQ2MzIWFRQGJzI2NTQm' +
  'IyIGFRQWkis8PCssOz4pEBEREA4TEwIcOCsrODgrLTZCEg8OExMODxIAAAIAKwLsAPkDsgALABcAAFMiJjU0NjMyFhUUBicyNjU0' +
  'JiMiBhUUFpIrPDwrLDs+KRARERAOExMC7DgrKzg3LC02QhIPDhMTDg4TAAABACv/pQHPAwsAAwAAVycBF3hNAVdNWx8DRx8AAQAr' +
  '/7sB5AIuAAMAAFcnARdsQQF4QUUqAkkq//8ARwDMAW8BMwYGAFoAAAABAD8BNAGKAYcAAwAAUzUhFT8BSwE0U1MAAAEAFv/0AVIB' +
  'XgAdAABXIiYnNxYWMzI2NTQmIyM1NzUjNSEVBxUWFhUUBga3QloFVQMrHiAlJSJBXrUBM281PClGDEA7CBwhIBcZGT8qDUVKNg0C' +
  'MDEkNx8A//8AFgFSAVICvAYHAOUAAAFeAAEAKwIeAYYCsAAdAABTJzc2NjMyFhcWFjMyNjc3FwcGBiMiJicmJiMiBgdsQSEOKRkV' +
  'IRAKFQwPEQcSQCAOKBoWIBEJFA4OEQcCHyg5GRcREAkREgsdKTgYGBEPChASCgAAAQArAuwBjgN5AB0AAFMnNzY2MzIWFxYWMzI2' +
  'NzcXBwYGIyImJyYmIyIGB2c8IBEoGxgfEQsVDg8TCBM8IBAoGxgfEgoVDg8TCQLtLi0XGhAPChASCxsvLBcaEA8JERMLAAABABoA' +
  'AAFQAWoAHAAAczU0Njc2NjU0JiMiBgcnNjYzMhYVFAYHBgYHMxUaQUQvLCQcGygDVgVWQUJUSkArJAHYKTpEDwscGBYZHCIGPkBA' +
  'NjY2DgoWFEYAAQAAAOoAXAAIAGQABQABAAAAAAAAAAAAAAAAAAMAAgAAAAAAAAAaAFkAhQCpAL8A0wEKASEBLQFPAWoBeQGWAa0B' +
  '1wH8AjMCYwKtAr4C3wLyAxEDLgNDA1sDnwPVBAoEQAR0BJAEzgTxBPwFBwUeBSoFYAWCBbIF6AYfBjgGdwaTBrYGyQboBwEHLAdD' +
  'B20Hfwe6B+8IDAhGCIwIqQkECUoJZgmCCbIJ4goACh4KLQo6Ck4KXQpmCnMKfQqGCpUKogqqCsAK3AroCvQLBAsgCz0LgwvKC9YL' +
  '4gvuC/cMAwxwDKwM9g0CDQ4NGQ0kDS8NOw1gDWwNdw2CDY4NmQ2kDbANuw3GDdEN3A3nDfIN/g4KDhUOIA4rDjYOQg5ODloOZQ5w' +
  'DnwOpA6vDrsOxg7RDtwO6A9QD1wPoA+rD7cPwg/ND9gP4w/uD/kQBBAPEBsQJxAyED0QSBBTEF4QthDBEM0Q2BDjEO8Q+hEyEXIR' +
  'mBH9EigSgRLQEvkTSBOYE8AT5hQhFC8UhRSUFKMUshTGFN8VCxUeFTIVRRVgFXMVoxWyFd4V5hXuFfYWAxYLFhgWIRYqFjMWQBZc' +
  'FngWnhawFsIW6BcOFyQXOhdUF2EXbheSF7YXwhfWGAMYAxgUGB0YQxhpGHcYhRiNGJoYxxjQGQEZMhleAAAAAQAAAAIAAArxZZ9f' +
  'Dzz1CAMD6AAAAADbnCKZAAAAAOaoXA3/s/7jBM8ENAAAAAYAAgAAAAAAAAODAF4A/wAAAnkAFAKXAC4CgwA0ApkALgIsAEUCFwBF' +
  'ApUANAKQAEUBAwBFAl4AIgJuAEUCHwBFA24ARQKcAEUCogA0AlsARQKiADQCeABFAmAAJQJMABkCnwBBAmoAFAN8ACACggAYAm0A' +
  'CQJAAC8CQQApAn8ASQJNADECfwAxAkUAMQG1ABsCfwAxAmcASQEFADYBB//sAi4ASQEFAEkDVwBJAmcASQJlADECfwBJAn8AMQGH' +
  'AEkCDQAsAckAGwJnAEUCIgAUAxQAKwJQAB4CZwBFAgcANgKGADQBvAANAlQALQJfACUCeQAbAlgAKQJpADQCLAAcAl4AIQJpACsB' +
  'YABJAWAAEQHKACUBygARAYkANAGDAAIBgP/0AP0ARQD9AEUBgP/zARwANwHsADcBHAA4ARwANwHsADgB7AA3ARwANwEfADcBHAA3' +
  'AR8ANwEfADcDAQA3AR8ANwEfADcCQwAkAkMAKwG2AEcCTgBHA34ARwDSABECbABEA/kARQJSACACFwAtAnkAFAJ5ABQCeQAUAnkA' +
  'FAJ5ABQCeQAUAzcAFAKDADQCmQAuAiwARQIsAEUCLABFAiwARQKVADQBA//+AQMAOAED/8UBA//JAQMANQKcAEUCogA0AqIANAKi' +
  'ADQCogA0AqIANAKiADQCYAAlAp8AQQKfAEECnwBBAp8AQQJtAAkCWwBFAkEAKQJBACkCQQApAkEAKQJBACkCQQApA3cAKQJNADEC' +
  'aAAxAkUAMQJFADECRQAxAkUAMQJ/ADEBBf/7AQUAPAEF/8cBBf/RAmcASQJlADECZQAxAmUAMQJlADECZQAxAmUAMQINACwChQBJ' +
  'AmcARQJnAEUCZwBFAmcARQJnAEUCZwBFAn8ASQGjACMBtAAiAeAAIQJdABMCzAA0AggAMgJ6ACkCbAApAmAAJQJ8ADYCbAADAlYA' +
  'NAKBABIC+QAcAzoAEQM4ABEDfAAWAmwAZQJsAGQCbABlAmwAZQJsAGQCbABkAmwAZQJsAEcCbAA1AmwAZAGHACEBJAArASQAKwG4' +
  'ACsBmgArAUcAKwAAACsBAwARAW0AGgFuABYAAAArAAAAKwAAACsAAAArAAAAKwAAACsAAAArAAAAKwAAACsAAAArAYcAEwAAACsA' +
  'AAArAscANALHAEQBBQBJAQf/7AJvAEUA/wAAAQMAEQEDABEAAAArAAAAKwAAACsAAAArAbYARwHJAD8BbgAWAW4AFgAAACsAAAAr' +
  'AW0AGgABAAAD2P7cAAAE+/+z/TgEzwABAAAAAAAAAAAAAAAAAAAA6gAEAjMCWAAFAAACigJYAAAASwKKAlgAAAFeADIBIwAAAAAA' +
  'AAAAAAAAAIAAAAcAAAAAAAAAAAAAAABGSwAAAMAAICAmA9j+3AAABH4BJAAAABEAAAAAAeYCvAAAACAAAwAAAAIAAAADAAAAFAAD' +
  'AAEAAAAUAAQBpAAAACAAIAAEAAAALwA5AEAAWgBgAHoAfgD/AR8BMQFfIBQgGiAdICb//wAAACAAMAA6AEEAWwBhAHsAoAEeATAB' +
  'XiATIBggHCAm//8AAAAGAAD/wQAA/7sAAAAAAAAAAAAA4EgAAOAy4C8AAQAgAAAAPAAAAEYAAABOAFQBEgEUARYAAAEWAAAAAAAA' +
  'AAEAVgBLAKsArQCyAGAASgBEAEUAYQC2AFIAWgBRAEYAUwBUALoAuQC7AFgAXwBAAEkAQQC9AF4AwQBCAEcAQwC+ANwAVwCwAK4A' +
  'rACvAEgApwDDAKkApQDXAL8A4wCqAMQAwAC8AMgAyQDCANsAqABdAMUAxwCmANgAswC0ALUAWQBiAGMAZABlAGYAZwBoAGkAawBs' +
  'AG0AbgBwAHEAcgBzAGoAdQB2AHcAeAB5AHoAtwB7AH0AfgB/AIAAgQCCAJ0AgwCEAIUAhgCHAIgAiQCKAIwAjQCOAI8AkQCSAJMA' +
  'lACLAJUAlgCXAJgAmQCaALgAmwCeAJ8AoAChAKIApACjAG8AkAB0ANkAfACcAEwATQBQAAAACABmAAMAAQQJAAAAxAAAAAMAAQQJ' +
  'AAEAJgDEAAMAAQQJAAIADgDqAAMAAQQJAAMANgD4AAMAAQQJAAQAJgDEAAMAAQQJAAUAGgEuAAMAAQQJAAYAJAFIAAMAAQQJAQAA' +
  'DAFsAEMAbwBwAHkAcgBpAGcAaAB0ACAAMgAwADIAMAAgAFQAaABlACAAUwBwAGEAYwBlACAARwByAG8AdABlAHMAawAgAFAAcgBv' +
  'AGoAZQBjAHQAIABBAHUAdABoAG8AcgBzACAAKABoAHQAdABwAHMAOgAvAC8AZwBpAHQAaAB1AGIALgBjAG8AbQAvAGYAbABvAHIA' +
  'aQBhAG4AawBhAHIAcwB0AGUAbgAvAHMAcABhAGMAZQAtAGcAcgBvAHQAZQBzAGsAKQBTAHAAYQBjAGUAIABHAHIAbwB0AGUAcwBr' +
  'ACAATABpAGcAaAB0AFIAZQBnAHUAbABhAHIAMgAuADAAMAAwADsARgBLADsAUwBwAGEAYwBlAEcAcgBvAHQAZQBzAGsALQBMAGkA' +
  'ZwBoAHQAVgBlAHIAcwBpAG8AbgAgADIALgAwADAAMABTAHAAYQBjAGUARwByAG8AdABlAHMAawAtAEwAaQBnAGgAdABXAGUAaQBn' +
  'AGgAdAAAAAMAAAAAAAD/nAAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAB//8ADwABAAAADAAAAAAAAAACAA0AAgAGAAEACAAQAAEA' +
  'EwAWAAEAGAAYAAEAGgAgAAEAIgAjAAEAJgAqAAEALQAwAAEAMgAyAAEANAA1AAEAaABoAAEAiQCJAAEA2QDZAAEAAAABAAEACAAB' +
  'AAAAFAAAAAAAAAACd2dodAEAAAA=';

/** Satori'nin beklediği biçim: `ArrayBuffer`. */
export function ogFontData(): ArrayBuffer {
  const bytes = Buffer.from(OG_FONT_BASE64, 'base64');
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
}

export const OG_FONT_NAME = 'Space Grotesk';
